// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2

package handler

import (
	"net/http"

	admin "dmh/api/internal/handler/admin"
	auth "dmh/api/internal/handler/auth"
	brand "dmh/api/internal/handler/brand"
	campaign "dmh/api/internal/handler/campaign"
	distributor "dmh/api/internal/handler/distributor"
	feedback "dmh/api/internal/handler/feedback"
	order "dmh/api/internal/handler/order"
	poster "dmh/api/internal/handler/poster"
	reward "dmh/api/internal/handler/reward"
	role "dmh/api/internal/handler/role"
	security "dmh/api/internal/handler/security"
	statistics "dmh/api/internal/handler/statistics"
	sync "dmh/api/internal/handler/sync"
	withdrawal "dmh/api/internal/handler/withdrawal"
	"dmh/api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/admin/brand-admin-relations",
				Handler: admin.ManageBrandAdminRelationHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/admin/users",
				Handler: admin.CreateUserHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/admin/users",
				Handler: admin.GetUsersHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/admin/users/:id",
				Handler: admin.GetUserHandler(serverCtx),
			},
			{
				Method:  http.MethodPut,
				Path:    "/admin/users/:id",
				Handler: admin.UpdateUserHandler(serverCtx),
			},
			{
				Method:  http.MethodDelete,
				Path:    "/admin/users/:id",
				Handler: admin.DeleteUserHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/admin/users/:id/reset-password",
				Handler: admin.ResetUserPasswordHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
		rest.WithPrefix("/api/v1"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/auth/login",
				Handler: auth.LoginHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/auth/refresh-token",
				Handler: auth.RefreshTokenHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/auth/register",
				Handler: auth.RegisterHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api/v1"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/auth/send-email-code",
				Handler: auth.SendEmailCodeHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/auth/send-phone-code",
				Handler: auth.SendPhoneCodeHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/auth/userinfo",
				Handler: auth.GetUserInfoHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/users/bind-email",
				Handler: auth.BindEmailHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/users/bind-phone",
				Handler: auth.BindPhoneHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/users/change-password",
				Handler: auth.ChangePasswordHandler(serverCtx),
			},
			{
				Method:  http.MethodPut,
				Path:    "/users/profile",
				Handler: auth.UpdateProfileHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
		rest.WithPrefix("/api/v1"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/brands",
				Handler: brand.CreateBrandHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/brands",
				Handler: brand.GetBrandsHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/brands/:brandId/assets/:id",
				Handler: brand.GetBrandAssetHandler(serverCtx),
			},
			{
				Method:  http.MethodPut,
				Path:    "/brands/:brandId/assets/:id",
				Handler: brand.UpdateBrandAssetHandler(serverCtx),
			},
			{
				Method:  http.MethodDelete,
				Path:    "/brands/:brandId/assets/:id",
				Handler: brand.DeleteBrandAssetHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/brands/:id",
				Handler: brand.GetBrandHandler(serverCtx),
			},
			{
				Method:  http.MethodPut,
				Path:    "/brands/:id",
				Handler: brand.UpdateBrandHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/brands/:id/assets",
				Handler: brand.CreateBrandAssetHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/brands/:id/assets",
				Handler: brand.GetBrandAssetsHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/brands/:id/stats",
				Handler: brand.GetBrandStatsHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
		rest.WithPrefix("/api/v1"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/campaign/page-config/:id",
				Handler: campaign.SavePageConfigHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/campaign/page-config/:id",
				Handler: campaign.GetPageConfigHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/campaigns",
				Handler: campaign.CreateCampaignHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/campaigns",
				Handler: campaign.GetCampaignsHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/campaigns/:id",
				Handler: campaign.GetCampaignHandler(serverCtx),
			},
			{
				Method:  http.MethodPut,
				Path:    "/campaigns/:id",
				Handler: campaign.UpdateCampaignHandler(serverCtx),
			},
			{
				Method:  http.MethodDelete,
				Path:    "/campaigns/:id",
				Handler: campaign.DeleteCampaignHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/campaigns/:id/payment-qrcode",
				Handler: campaign.GetPaymentQrcodeHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
		rest.WithPrefix("/api/v1"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/feedback",
				Handler: feedback.CreateFeedbackRouteHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/feedback/list",
				Handler: feedback.ListFeedbackRouteHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/feedback/detail",
				Handler: feedback.GetFeedbackRouteHandler(serverCtx),
			},
			{
				Method:  http.MethodPut,
				Path:    "/feedback/status",
				Handler: feedback.UpdateFeedbackStatusRouteHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/feedback/satisfaction-survey",
				Handler: feedback.SubmitSatisfactionSurveyRouteHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/feedback/faq",
				Handler: feedback.ListFAQRouteHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/feedback/faq/helpful",
				Handler: feedback.MarkFAQHelpfulRouteHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/feedback/feature-usage",
				Handler: feedback.RecordFeatureUsageRouteHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/feedback/statistics",
				Handler: feedback.GetFeedbackStatisticsRouteHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
		rest.WithPrefix("/api/v1"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/distributor/applications",
				Handler: distributor.GetDistributorApplicationsHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/distributor/applications/:id",
				Handler: distributor.GetDistributorApplicationHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/distributor/apply",
				Handler: distributor.DistributorApplyHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/distributor/dashboard",
				Handler: distributor.GetMyDistributorDashboardHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/distributor/link/generate",
				Handler: distributor.GenerateDistributorLinkHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/distributor/links",
				Handler: distributor.GetDistributorLinksHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/distributor/qrcode/:linkCode",
				Handler: distributor.GetDistributorQrcodeHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/distributor/rewards/:brandId",
				Handler: distributor.GetDistributorRewardsHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/distributor/statistics/:brandId",
				Handler: distributor.GetDistributorStatisticsHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/distributor/status/:brandId",
				Handler: distributor.GetMyDistributorStatusHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/distributor/subordinates/:brandId",
				Handler: distributor.GetDistributorSubordinatesHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
		rest.WithPrefix("/api/v1"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/:brandId/distributor/applications",
				Handler: distributor.GetBrandDistributorApplicationsHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/:brandId/distributor/applications/:id",
				Handler: distributor.GetBrandDistributorApplicationHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/:brandId/distributor/approve/:id",
				Handler: distributor.ApproveDistributorApplicationHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/:brandId/distributor/level-rewards",
				Handler: distributor.GetDistributorLevelRewardsHandler(serverCtx),
			},
			{
				Method:  http.MethodPut,
				Path:    "/:brandId/distributor/level-rewards",
				Handler: distributor.SetDistributorLevelRewardsHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/:brandId/distributors",
				Handler: distributor.GetBrandDistributorsHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/:brandId/distributors/:id",
				Handler: distributor.GetBrandDistributorHandler(serverCtx),
			},
			{
				Method:  http.MethodPut,
				Path:    "/distributors/:id/level",
				Handler: distributor.UpdateDistributorLevelHandler(serverCtx),
			},
			{
				Method:  http.MethodPut,
				Path:    "/distributors/:id/status",
				Handler: distributor.UpdateDistributorStatusHandler(serverCtx),
			},
		},
		// 临时禁用JWT以便测试
		// rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
		rest.WithPrefix("/api/v1"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/distributor/info/:linkCode",
				Handler: distributor.GetDistributorByCodeHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/distributor/track/:linkCode",
				Handler: distributor.TrackDistributorLinkHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api/v1"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/orders",
				Handler: order.CreateOrderHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/orders/:id",
				Handler: order.GetOrderHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/orders/payment/callback",
				Handler: order.PaymentCallbackHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/orders/scan",
				Handler: order.ScanOrderHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/orders/verification-records",
				Handler: order.GetVerificationRecordsHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/orders/list",
				Handler: order.GetOrdersHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api/v1"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/orders/unverify",
				Handler: order.UnverifyOrderHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/orders/verify",
				Handler: order.VerifyOrderHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
		rest.WithPrefix("/api/v1"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/campaigns/:id/poster",
				Handler: poster.GenerateCampaignPosterHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/distributors/:id/poster",
				Handler: poster.GenerateDistributorPosterHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/poster/records",
				Handler: poster.GetPosterRecordsHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/poster/templates",
				Handler: poster.GetPosterTemplatesHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api/v1"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/rewards/:userId",
				Handler: reward.GetRewardsHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/rewards/balance/:userId",
				Handler: reward.GetBalanceHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
		rest.WithPrefix("/api/v1"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/permissions",
				Handler: role.GetPermissionsHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/roles",
				Handler: role.GetRolesHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/roles/permissions",
				Handler: role.ConfigRolePermissionsHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/users/:id/permissions",
				Handler: role.GetUserPermissionsHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
		rest.WithPrefix("/api/v1"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/security/audit-logs",
				Handler: security.GetAuditLogsHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/security/check-password-strength",
				Handler: security.CheckPasswordStrengthHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/security/events",
				Handler: security.GetSecurityEventsHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/security/events/:eventId/handle",
				Handler: security.HandleSecurityEventHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/security/force-logout/:userId",
				Handler: security.ForceLogoutUserHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/security/login-attempts",
				Handler: security.GetLoginAttemptsHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/security/password-policy",
				Handler: security.GetPasswordPolicyHandler(serverCtx),
			},
			{
				Method:  http.MethodPut,
				Path:    "/security/password-policy",
				Handler: security.UpdatePasswordPolicyHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/security/sessions",
				Handler: security.GetUserSessionsHandler(serverCtx),
			},
			{
				Method:  http.MethodDelete,
				Path:    "/security/sessions/:sessionId",
				Handler: security.RevokeSessionHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
		rest.WithPrefix("/api/v1"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/dashboard-stats",
				Handler: statistics.GetDashboardStatsHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/sync/health",
				Handler: sync.GetSyncHealthHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/sync/retry/:orderId",
				Handler: sync.RetrySynHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/sync/statistics",
				Handler: sync.GetSyncStatsHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/sync/status/:orderId",
				Handler: sync.GetSyncStatusHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
		rest.WithPrefix("/api/v1"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/withdrawals",
				Handler: withdrawal.ApplyWithdrawalHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/withdrawals",
				Handler: withdrawal.GetWithdrawalsHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/withdrawals/:id",
				Handler: withdrawal.GetWithdrawalHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/withdrawals/:id/approve",
				Handler: withdrawal.ApproveWithdrawalHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
		rest.WithPrefix("/api/v1"),
	)
}
