// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2

package handler

import (
	"net/http"

	admin "dmh/api/internal/handler/admin"
	auth "dmh/api/internal/handler/auth"
	brand "dmh/api/internal/handler/brand"
	campaign "dmh/api/internal/handler/campaign"
	menu "dmh/api/internal/handler/menu"
	order "dmh/api/internal/handler/order"
	reward "dmh/api/internal/handler/reward"
	role "dmh/api/internal/handler/role"
	security "dmh/api/internal/handler/security"
	sync "dmh/api/internal/handler/sync"
	withdrawal "dmh/api/internal/handler/withdrawal"
	"dmh/api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/admin/users",
				Handler: admin.CreateUserHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/admin/users",
				Handler: admin.GetUsersHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/admin/users/:id",
				Handler: admin.GetUserHandler(serverCtx),
			},
			{
				Method:  http.MethodPut,
				Path:    "/admin/users/:id",
				Handler: admin.UpdateUserHandler(serverCtx),
			},
			{
				Method:  http.MethodDelete,
				Path:    "/admin/users/:id",
				Handler: admin.DeleteUserHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/admin/users/:id/reset-password",
				Handler: admin.ResetUserPasswordHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
		rest.WithPrefix("/api/v1"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/auth/login",
				Handler: auth.LoginHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/auth/refresh-token",
				Handler: auth.RefreshTokenHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/auth/register",
				Handler: auth.RegisterHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api/v1"),
	)

	// 公开的H5活动路由（无需认证）
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/h5/campaigns",
				Handler: campaign.GetCampaignsHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/h5/campaigns/:id",
				Handler: campaign.GetCampaignHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api/v1"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/auth/send-email-code",
				Handler: auth.SendEmailCodeHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/auth/send-phone-code",
				Handler: auth.SendPhoneCodeHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/auth/userinfo",
				Handler: auth.GetUserInfoHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/users/bind-email",
				Handler: auth.BindEmailHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/users/bind-phone",
				Handler: auth.BindPhoneHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/users/change-password",
				Handler: auth.ChangePasswordHandler(serverCtx),
			},
			{
				Method:  http.MethodPut,
				Path:    "/users/profile",
				Handler: auth.UpdateProfileHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
		rest.WithPrefix("/api/v1"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/brands",
				Handler: brand.CreateBrandHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/brands",
				Handler: brand.GetBrandsHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/brands/:brandId/assets/:id",
				Handler: brand.GetBrandAssetHandler(serverCtx),
			},
			{
				Method:  http.MethodPut,
				Path:    "/brands/:brandId/assets/:id",
				Handler: brand.UpdateBrandAssetHandler(serverCtx),
			},
			{
				Method:  http.MethodDelete,
				Path:    "/brands/:brandId/assets/:id",
				Handler: brand.DeleteBrandAssetHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/brands/:id",
				Handler: brand.GetBrandHandler(serverCtx),
			},
			{
				Method:  http.MethodPut,
				Path:    "/brands/:id",
				Handler: brand.UpdateBrandHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/brands/:id/assets",
				Handler: brand.CreateBrandAssetHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/brands/:id/assets",
				Handler: brand.GetBrandAssetsHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/brands/:id/stats",
				Handler: brand.GetBrandStatsHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
		rest.WithPrefix("/api/v1"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/campaign/page-config/:id",
				Handler: campaign.SavePageConfigHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/campaign/page-config/:id",
				Handler: campaign.GetPageConfigHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/campaigns",
				Handler: campaign.CreateCampaignHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/campaigns",
				Handler: campaign.GetCampaignsHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/campaigns/:id",
				Handler: campaign.GetCampaignHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
		rest.WithPrefix("/api/v1"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/menus",
				Handler: menu.CreateMenuHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/menus",
				Handler: menu.GetMenusHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/menus/:id",
				Handler: menu.GetMenuHandler(serverCtx),
			},
			{
				Method:  http.MethodPut,
				Path:    "/menus/:id",
				Handler: menu.UpdateMenuHandler(serverCtx),
			},
			{
				Method:  http.MethodDelete,
				Path:    "/menus/:id",
				Handler: menu.DeleteMenuHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/roles/menus",
				Handler: menu.ConfigRoleMenusHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/users/menus",
				Handler: menu.GetUserMenusHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
		rest.WithPrefix("/api/v1"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/orders",
				Handler: order.CreateOrderHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/orders/:id",
				Handler: order.GetOrderHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/orders/payment/callback",
				Handler: order.PaymentCallbackHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
		rest.WithPrefix("/api/v1"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/rewards/:userId",
				Handler: reward.GetRewardsHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/rewards/balance/:userId",
				Handler: reward.GetBalanceHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
		rest.WithPrefix("/api/v1"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/permissions",
				Handler: role.GetPermissionsHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/roles",
				Handler: role.GetRolesHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/roles/permissions",
				Handler: role.ConfigRolePermissionsHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/users/:id/permissions",
				Handler: role.GetUserPermissionsHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
		rest.WithPrefix("/api/v1"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/security/audit-logs",
				Handler: security.GetAuditLogsHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/security/check-password-strength",
				Handler: security.CheckPasswordStrengthHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/security/events",
				Handler: security.GetSecurityEventsHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/security/events/:eventId/handle",
				Handler: security.HandleSecurityEventHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/security/force-logout/:userId",
				Handler: security.ForceLogoutUserHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/security/login-attempts",
				Handler: security.GetLoginAttemptsHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/security/password-policy",
				Handler: security.GetPasswordPolicyHandler(serverCtx),
			},
			{
				Method:  http.MethodPut,
				Path:    "/security/password-policy",
				Handler: security.UpdatePasswordPolicyHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/security/sessions",
				Handler: security.GetUserSessionsHandler(serverCtx),
			},
			{
				Method:  http.MethodDelete,
				Path:    "/security/sessions/:sessionId",
				Handler: security.RevokeSessionHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
		rest.WithPrefix("/api/v1"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/sync/health",
				Handler: sync.GetSyncHealthHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/sync/retry/:orderId",
				Handler: sync.RetrySynHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/sync/statistics",
				Handler: sync.GetSyncStatsHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/sync/status/:orderId",
				Handler: sync.GetSyncStatusHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
		rest.WithPrefix("/api/v1"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/withdrawals",
				Handler: withdrawal.ApplyWithdrawalHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/withdrawals",
				Handler: withdrawal.GetWithdrawalsHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/withdrawals/:id",
				Handler: withdrawal.GetWithdrawalHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/withdrawals/:id/approve",
				Handler: withdrawal.ApproveWithdrawalHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
		rest.WithPrefix("/api/v1"),
	)
}
