// Code generated by goctl. DO NOT EDIT.
package withdrawal

import (
	"context"
	"testing"
	"time"

	"dmh/api/internal/svc"
	"dmh/api/internal/types"
	"dmh/model"

	"github.com/stretchr/testify/assert"
	"gorm.io/driver/sqlite"
	"gorm.io/gorm"
)

func setupWithdrawalTestDB() *gorm.DB {
	db, _ := gorm.Open(sqlite.Open(":memory:"), &gorm.Config{})
	db.AutoMigrate(&model.Withdrawal{}, &model.User{}, &model.Distributor{}, &model.Brand{}, &model.UserBalance{})
	return db
}

func TestApplyWithdrawalLogic(t *testing.T) {
	db := setupWithdrawalTestDB()

	// 创建测试用户
	user := &model.User{
		Id:       1,
		Username: "testuser",
		Phone:    "13800138000",
		Role:     "participant",
		Status:   "active",
	}
	db.Create(user)

	// 创建测试分销商
	distributor := &model.Distributor{
		Id:            1,
		UserId:        1,
		Level:         1,
		TotalEarnings: 1000,
		Status:        "normal",
	}
	db.Create(distributor)

	// 创建测试品牌
	brand := &model.Brand{
		Id:   1,
		Name: "Test Brand",
	}
	db.Create(brand)

	// 创建用户余额
	balance := &model.UserBalance{
		UserId:  1,
		Balance: 500,
	}
	db.Create(balance)

	svcCtx := &svc.ServiceContext{DB: db}
	logic := NewApplyWithdrawalLogic(context.Background(), svcCtx)

	tests := []struct {
		name        string
		req         *types.WithdrawalApplyReq
		userId      int64
		expectError bool
		errorMsg    string
	}{
		{
			name: "成功申请提现",
			req: &types.WithdrawalApplyReq{
				Amount:      100,
				BankName:    "ICBC",
				BankAccount: "6222021234567890",
				AccountName: "张三",
			},
			userId:      1,
			expectError: false,
		},
		{
			name: "金额小于10",
			req: &types.WithdrawalApplyReq{
				Amount:      5,
				BankName:    "ICBC",
				BankAccount: "6222021234567890",
				AccountName: "张三",
			},
			userId:      1,
			expectError: true,
			errorMsg:    "amount must be at least 10",
		},
		{
			name: "余额不足",
			req: &types.WithdrawalApplyReq{
				Amount:      1000,
				BankName:    "ICBC",
				BankAccount: "6222021234567890",
				AccountName: "张三",
			},
			userId:      1,
			expectError: true,
			errorMsg:    "insufficient balance",
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			// 重置余额
			db.Model(&model.UserBalance{}).Where("user_id = ?", 1).Update("balance", 500)
			db.Where("user_id = ? AND status = ?", 1, "pending").Delete(&model.Withdrawal{})

			resp, err := logic.ApplyWithdrawal(tt.req, tt.userId)

			if tt.expectError {
				assert.Error(t, err)
				assert.Nil(t, resp)
				if tt.errorMsg != "" {
					assert.Contains(t, err.Error(), tt.errorMsg)
				}
			} else {
				assert.NoError(t, err)
				assert.NotNil(t, resp)
				assert.Equal(t, tt.req.Amount, resp.Amount)
				assert.Equal(t, "pending", resp.Status)
			}
		})
	}
}

func TestApproveWithdrawalLogic(t *testing.T) {
	db := setupWithdrawalTestDB()

	// 创建测试数据
	user := &model.User{Id: 1, Username: "testuser", Phone: "13800138000"}
	distributor := &model.Distributor{Id: 1, UserId: 1}
	brand := &model.Brand{Id: 1, Name: "Test Brand"}
	balance := &model.UserBalance{UserId: 1, Balance: 500}
	db.Create(user)
	db.Create(distributor)
	db.Create(brand)
	db.Create(balance)

	// 创建提现申请
	withdrawal := &model.Withdrawal{
		ID:            1,
		UserID:        1,
		BrandId:       1,
		DistributorId: 1,
		Amount:        100,
		Status:        "pending",
		BankName:      "ICBC",
		BankAccount:   "6222021234567890",
		AccountName:   "张三",
	}
	db.Create(withdrawal)

	svcCtx := &svc.ServiceContext{DB: db}
	logic := NewApproveWithdrawalLogic(context.Background(), svcCtx)

	tests := []struct {
		name         string
		withdrawalId int64
		req          *types.WithdrawalApproveReq
		adminId      int64
		expectError  bool
		errorMsg     string
	}{
		{
			name:         "成功批准提现",
			withdrawalId: 1,
			req: &types.WithdrawalApproveReq{
				Status: "approved",
			},
			adminId:     1,
			expectError: false,
		},
		{
			name:         "拒绝提现并退款",
			withdrawalId: 1,
			req: &types.WithdrawalApproveReq{
				Status: "rejected",
				Remark: "审核不通过",
			},
			adminId:     1,
			expectError: false,
		},
		{
			name:         "无效状态",
			withdrawalId: 1,
			req: &types.WithdrawalApproveReq{
				Status: "invalid",
			},
			adminId:     1,
			expectError: true,
			errorMsg:    "invalid status",
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			// 重置提现状态
			db.Model(&model.Withdrawal{}).Where("id = ?", 1).Update("status", "pending")
			db.Model(&model.UserBalance{}).Where("user_id = ?", 1).Update("balance", 500)

			resp, err := logic.ApproveWithdrawal(tt.withdrawalId, tt.req, tt.adminId)

			if tt.expectError {
				assert.Error(t, err)
				if tt.errorMsg != "" {
					assert.Contains(t, err.Error(), tt.errorMsg)
				}
			} else {
				assert.NoError(t, err)
				assert.NotNil(t, resp)
				assert.Equal(t, tt.req.Status, resp.Status)

				// 检查余额是否正确更新
				var newBalance model.UserBalance
				db.Where("user_id = ?", 1).First(&newBalance)
				if tt.req.Status == "rejected" {
					assert.Equal(t, float64(600), newBalance.Balance)
				}
			}
		})
	}
}

func TestGetWithdrawalsLogic(t *testing.T) {
	db := setupWithdrawalTestDB()

	// 创建测试数据
	user := &model.User{Id: 1, Username: "testuser", Phone: "13800138000", RealName: "张三"}
	distributor := &model.Distributor{Id: 1, UserId: 1}
	brand := &model.Brand{Id: 1, Name: "Test Brand"}
	db.Create(user)
	db.Create(distributor)
	db.Create(brand)

	now := time.Now()
	withdrawals := []model.Withdrawal{
		{
			ID:            1,
			UserID:        1,
			BrandId:       1,
			DistributorId: 1,
			Amount:        100,
			Status:        "pending",
			BankName:      "ICBC",
			BankAccount:   "6222021234567890",
			AccountName:   "张三",
			CreatedAt:     now,
		},
		{
			ID:            2,
			UserID:        1,
			BrandId:       1,
			DistributorId: 1,
			Amount:        200,
			Status:        "approved",
			BankName:      "CCB",
			BankAccount:   "6222021234567891",
			AccountName:   "张三",
			CreatedAt:     now.Add(-1 * time.Hour),
		},
	}
	db.Create(&withdrawals)

	svcCtx := &svc.ServiceContext{DB: db}
	logic := NewGetWithdrawalsLogic(context.Background(), svcCtx)

	tests := []struct {
		name        string
		req         *types.WithdrawalListReq
		expectTotal int64
		expectError bool
	}{
		{
			name: "获取所有提现记录",
			req: &types.WithdrawalListReq{
				Page:     1,
				PageSize: 10,
			},
			expectTotal: 2,
			expectError: false,
		},
		{
			name: "按状态筛选",
			req: &types.WithdrawalListReq{
				Page:     1,
				PageSize: 10,
				Status:   "pending",
			},
			expectTotal: 1,
			expectError: false,
		},
		{
			name: "按用户筛选",
			req: &types.WithdrawalListReq{
				Page:     1,
				PageSize: 10,
				UserId:   1,
			},
			expectTotal: 2,
			expectError: false,
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			resp, err := logic.GetWithdrawals(tt.req)

			if tt.expectError {
				assert.Error(t, err)
			} else {
				assert.NoError(t, err)
				assert.NotNil(t, resp)
				assert.Equal(t, tt.expectTotal, resp.Total)
			}
		})
	}
}

func TestGetWithdrawalLogic(t *testing.T) {
	db := setupWithdrawalTestDB()

	user := &model.User{Id: 1, Username: "testuser", Phone: "13800138000", RealName: "张三"}
	distributor := &model.Distributor{Id: 1, UserId: 1}
	brand := &model.Brand{Id: 1, Name: "Test Brand"}
	db.Create(user)
	db.Create(distributor)
	db.Create(brand)

	withdrawal := &model.Withdrawal{
		ID:            1,
		UserID:        1,
		BrandId:       1,
		DistributorId: 1,
		Amount:        100,
		Status:        "pending",
		BankName:      "ICBC",
		BankAccount:   "6222021234567890",
		AccountName:   "张三",
	}
	db.Create(withdrawal)

	svcCtx := &svc.ServiceContext{DB: db}
	logic := NewGetWithdrawalLogic(context.Background(), svcCtx)

	tests := []struct {
		name         string
		withdrawalId int64
		expectError  bool
		errorMsg     string
	}{
		{
			name:         "成功获取提现详情",
			withdrawalId: 1,
			expectError:  false,
		},
		{
			name:         "提现记录不存在",
			withdrawalId: 999,
			expectError:  true,
			errorMsg:     "withdrawal not found",
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			resp, err := logic.GetWithdrawal(tt.withdrawalId)

			if tt.expectError {
				assert.Error(t, err)
				if tt.errorMsg != "" {
					assert.Contains(t, err.Error(), tt.errorMsg)
				}
			} else {
				assert.NoError(t, err)
				assert.NotNil(t, resp)
				assert.Equal(t, tt.withdrawalId, resp.Id)
				assert.Equal(t, "testuser", resp.Username)
			}
		})
	}
}
