// Code generated by goctl. DO NOT EDIT.
package withdrawal

import (
	"context"
	"testing"
	"time"

	"dmh/api/internal/handler/testutil"
	"dmh/api/internal/svc"
	"dmh/api/internal/types"
	"dmh/model"

	"github.com/stretchr/testify/assert"
	"gorm.io/gorm"
)

func setupWithdrawalTestDB(t *testing.T) *gorm.DB {
	t.Helper()
	db := testutil.SetupGormTestDB(t)
	db.AutoMigrate(&model.Withdrawal{}, &model.User{}, &model.Distributor{}, &model.Brand{}, &model.UserBalance{})
	testutil.ClearTables(db, "withdrawals", "user_balances", "distributors", "brands", "users")
	return db
}

func TestApplyWithdrawalLogic(t *testing.T) {
	db := setupWithdrawalTestDB(t)

	// 创建测试用户
	user := &model.User{
		Id:       1,
		Username: "testuser",
		Phone:    "13800138000",
		Role:     "participant",
		Status:   "active",
	}
	db.Create(user)

	// 创建测试品牌
	brand := &model.Brand{
		Id:     1,
		Name:   "Test Brand",
		Status: "active",
	}
	db.Create(brand)

	// 创建测试分销商
	distributor := &model.Distributor{
		Id:            1,
		UserId:        1,
		BrandId:       1,
		Level:         1,
		TotalEarnings: 1000,
		Status:        "active",
	}
	db.Create(distributor)

	// 创建用户余额
	balance := &model.UserBalance{
		UserId:  1,
		Balance: 500,
	}
	db.Create(balance)

	svcCtx := &svc.ServiceContext{DB: db}
	logic := NewApplyWithdrawalLogic(context.Background(), svcCtx)

	tests := []struct {
		name        string
		req         *types.WithdrawalApplyReq
		userId      int64
		expectError bool
		errorMsg    string
	}{
		{
			name: "成功申请提现",
			req: &types.WithdrawalApplyReq{
				Amount:      100,
				BankName:    "ICBC",
				BankAccount: "6222021234567890",
				AccountName: "张三",
			},
			userId:      1,
			expectError: false,
		},
		{
			name: "金额小于10",
			req: &types.WithdrawalApplyReq{
				Amount:      5,
				BankName:    "ICBC",
				BankAccount: "6222021234567890",
				AccountName: "张三",
			},
			userId:      1,
			expectError: true,
			errorMsg:    "amount must be at least 10",
		},
		{
			name: "余额不足",
			req: &types.WithdrawalApplyReq{
				Amount:      1000,
				BankName:    "ICBC",
				BankAccount: "6222021234567890",
				AccountName: "张三",
			},
			userId:      1,
			expectError: true,
			errorMsg:    "insufficient balance",
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			// 重置余额
			db.Model(&model.UserBalance{}).Where("user_id = ?", 1).Update("balance", 500)
			db.Where("user_id = ? AND status = ?", 1, "pending").Delete(&model.Withdrawal{})

			resp, err := logic.ApplyWithdrawal(tt.req, tt.userId)

			if tt.expectError {
				assert.Error(t, err)
				assert.Nil(t, resp)
				if tt.errorMsg != "" {
					assert.Contains(t, err.Error(), tt.errorMsg)
				}
			} else {
				assert.NoError(t, err)
				assert.NotNil(t, resp)
				assert.Equal(t, tt.req.Amount, resp.Amount)
				assert.Equal(t, "pending", resp.Status)
			}
		})
	}
}

func TestApproveWithdrawalLogic(t *testing.T) {
	db := setupWithdrawalTestDB(t)

	// 创建测试数据
	user := &model.User{Id: 1, Username: "testuser", Phone: "13800138000"}
	distributor := &model.Distributor{Id: 1, UserId: 1}
	brand := &model.Brand{Id: 1, Name: "Test Brand"}
	balance := &model.UserBalance{UserId: 1, Balance: 500}
	db.Create(user)
	db.Create(distributor)
	db.Create(brand)
	db.Create(balance)

	// 创建提现申请
	withdrawal := &model.Withdrawal{
		ID:            1,
		UserID:        1,
		BrandId:       1,
		DistributorId: 1,
		Amount:        100,
		Status:        "pending",
		BankName:      "ICBC",
		BankAccount:   "6222021234567890",
		AccountName:   "张三",
	}
	db.Create(withdrawal)

	svcCtx := &svc.ServiceContext{DB: db}
	logic := NewApproveWithdrawalLogic(context.Background(), svcCtx)

	tests := []struct {
		name         string
		withdrawalId int64
		req          *types.WithdrawalApproveReq
		adminId      int64
		expectError  bool
		errorMsg     string
	}{
		{
			name:         "成功批准提现",
			withdrawalId: 1,
			req: &types.WithdrawalApproveReq{
				Status: "approved",
			},
			adminId:     1,
			expectError: false,
		},
		{
			name:         "拒绝提现并退款",
			withdrawalId: 1,
			req: &types.WithdrawalApproveReq{
				Status: "rejected",
				Remark: "审核不通过",
			},
			adminId:     1,
			expectError: false,
		},
		{
			name:         "无效状态",
			withdrawalId: 1,
			req: &types.WithdrawalApproveReq{
				Status: "invalid",
			},
			adminId:     1,
			expectError: true,
			errorMsg:    "invalid status",
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			// 重置提现状态
			db.Model(&model.Withdrawal{}).Where("id = ?", 1).Update("status", "pending")
			db.Model(&model.UserBalance{}).Where("user_id = ?", 1).Update("balance", 500)

			resp, err := logic.ApproveWithdrawal(tt.withdrawalId, tt.req, tt.adminId)

			if tt.expectError {
				assert.Error(t, err)
				if tt.errorMsg != "" {
					assert.Contains(t, err.Error(), tt.errorMsg)
				}
			} else {
				assert.NoError(t, err)
				assert.NotNil(t, resp)
				assert.Equal(t, tt.req.Status, resp.Status)

				// 检查余额是否正确更新
				var newBalance model.UserBalance
				db.Where("user_id = ?", 1).First(&newBalance)
				if tt.req.Status == "rejected" {
					assert.Equal(t, float64(600), newBalance.Balance)
				}
			}
		})
	}
}

func TestGetWithdrawalsLogic(t *testing.T) {
	db := setupWithdrawalTestDB(t)

	// 创建测试数据
	user := &model.User{Id: 1, Username: "testuser", Phone: "13800138000", RealName: "张三"}
	distributor := &model.Distributor{Id: 1, UserId: 1}
	brand := &model.Brand{Id: 1, Name: "Test Brand"}
	db.Create(user)
	db.Create(distributor)
	db.Create(brand)

	now := time.Now()
	withdrawals := []model.Withdrawal{
		{
			ID:            1,
			UserID:        1,
			BrandId:       1,
			DistributorId: 1,
			Amount:        100,
			Status:        "pending",
			BankName:      "ICBC",
			BankAccount:   "6222021234567890",
			AccountName:   "张三",
			CreatedAt:     now,
		},
		{
			ID:            2,
			UserID:        1,
			BrandId:       1,
			DistributorId: 1,
			Amount:        200,
			Status:        "approved",
			BankName:      "CCB",
			BankAccount:   "6222021234567891",
			AccountName:   "张三",
			CreatedAt:     now.Add(-1 * time.Hour),
		},
	}
	db.Create(&withdrawals)

	svcCtx := &svc.ServiceContext{DB: db}
	logic := NewGetWithdrawalsLogic(context.Background(), svcCtx)

	tests := []struct {
		name        string
		req         *types.WithdrawalListReq
		expectTotal int64
		expectError bool
	}{
		{
			name: "获取所有提现记录",
			req: &types.WithdrawalListReq{
				Page:     1,
				PageSize: 10,
			},
			expectTotal: 2,
			expectError: false,
		},
		{
			name: "按状态筛选",
			req: &types.WithdrawalListReq{
				Page:     1,
				PageSize: 10,
				Status:   "pending",
			},
			expectTotal: 1,
			expectError: false,
		},
		{
			name: "按用户筛选",
			req: &types.WithdrawalListReq{
				Page:     1,
				PageSize: 10,
				UserId:   1,
			},
			expectTotal: 2,
			expectError: false,
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			resp, err := logic.GetWithdrawals(tt.req)

			if tt.expectError {
				assert.Error(t, err)
			} else {
				assert.NoError(t, err)
				assert.NotNil(t, resp)
				assert.Equal(t, tt.expectTotal, resp.Total)
			}
		})
	}
}

func TestGetWithdrawalLogic(t *testing.T) {
	db := setupWithdrawalTestDB(t)

	user := &model.User{Id: 1, Username: "testuser", Phone: "13800138000", RealName: "张三"}
	distributor := &model.Distributor{Id: 1, UserId: 1}
	brand := &model.Brand{Id: 1, Name: "Test Brand"}
	db.Create(user)
	db.Create(distributor)
	db.Create(brand)

	withdrawal := &model.Withdrawal{
		ID:            1,
		UserID:        1,
		BrandId:       1,
		DistributorId: 1,
		Amount:        100,
		Status:        "pending",
		BankName:      "ICBC",
		BankAccount:   "6222021234567890",
		AccountName:   "张三",
	}
	db.Create(withdrawal)

	svcCtx := &svc.ServiceContext{DB: db}
	logic := NewGetWithdrawalLogic(context.Background(), svcCtx)

	tests := []struct {
		name         string
		withdrawalId int64
		expectError  bool
		errorMsg     string
	}{
		{
			name:         "成功获取提现详情",
			withdrawalId: 1,
			expectError:  false,
		},
		{
			name:         "提现记录不存在",
			withdrawalId: 999,
			expectError:  true,
			errorMsg:     "withdrawal not found",
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			resp, err := logic.GetWithdrawal(tt.withdrawalId)

			if tt.expectError {
				assert.Error(t, err)
				if tt.errorMsg != "" {
					assert.Contains(t, err.Error(), tt.errorMsg)
				}
			} else {
				assert.NoError(t, err)
				assert.NotNil(t, resp)
				assert.Equal(t, tt.withdrawalId, resp.Id)
				assert.Equal(t, "testuser", resp.Username)
			}
		})
	}
}

func TestApplyWithdrawal_AmountZeroOrNegative(t *testing.T) {
	db := setupWithdrawalTestDB(t)

	user := &model.User{Id: 100, Username: "testuser_zero", Phone: "13900139000", Role: "participant", Status: "active"}
	db.Create(user)

	balance := &model.UserBalance{UserId: 100, Balance: 500}
	db.Create(balance)

	svcCtx := &svc.ServiceContext{DB: db}
	logic := NewApplyWithdrawalLogic(context.Background(), svcCtx)

	req := &types.WithdrawalApplyReq{
		Amount:      0,
		BankName:    "ICBC",
		BankAccount: "6222021234567890",
		AccountName: "张三",
	}

	resp, err := logic.ApplyWithdrawal(req, 100)
	assert.Error(t, err)
	assert.Nil(t, resp)
	assert.Contains(t, err.Error(), "amount must be greater than 0")
}

func TestApplyWithdrawal_UserBalanceNotFound(t *testing.T) {
	db := setupWithdrawalTestDB(t)

	user := &model.User{Id: 101, Username: "testuser_nobalance", Phone: "13900139001", Role: "participant", Status: "active"}
	db.Create(user)
	// No UserBalance created

	svcCtx := &svc.ServiceContext{DB: db}
	logic := NewApplyWithdrawalLogic(context.Background(), svcCtx)

	req := &types.WithdrawalApplyReq{
		Amount:      100,
		BankName:    "ICBC",
		BankAccount: "6222021234567890",
		AccountName: "张三",
	}

	resp, err := logic.ApplyWithdrawal(req, 101)
	assert.Error(t, err)
	assert.Nil(t, resp)
	assert.Contains(t, err.Error(), "failed to get user balance")
}

func TestApplyWithdrawal_PendingWithdrawalExists(t *testing.T) {
	db := setupWithdrawalTestDB(t)

	user := &model.User{Id: 102, Username: "testuser_pending", Phone: "13900139002", Role: "participant", Status: "active"}
	db.Create(user)

	balance := &model.UserBalance{UserId: 102, Balance: 500}
	db.Create(balance)

	// Create existing pending withdrawal
	existingWithdrawal := &model.Withdrawal{
		UserID:      102,
		Amount:      50,
		Status:      "pending",
		BankName:    "ICBC",
		BankAccount: "6222021234567890",
		AccountName: "张三",
	}
	db.Create(existingWithdrawal)

	svcCtx := &svc.ServiceContext{DB: db}
	logic := NewApplyWithdrawalLogic(context.Background(), svcCtx)

	req := &types.WithdrawalApplyReq{
		Amount:      100,
		BankName:    "CCB",
		BankAccount: "6222021234567891",
		AccountName: "李四",
	}

	resp, err := logic.ApplyWithdrawal(req, 102)
	assert.Error(t, err)
	assert.Nil(t, resp)
	assert.Contains(t, err.Error(), "pending withdrawal exists")
}

func TestApproveWithdrawal_NotFound(t *testing.T) {
	db := setupWithdrawalTestDB(t)

	svcCtx := &svc.ServiceContext{DB: db}
	logic := NewApproveWithdrawalLogic(context.Background(), svcCtx)

	req := &types.WithdrawalApproveReq{Status: "approved"}
	resp, err := logic.ApproveWithdrawal(99999, req, 1)

	assert.Error(t, err)
	assert.Nil(t, resp)
	assert.Contains(t, err.Error(), "withdrawal not found")
}

func TestApproveWithdrawal_AlreadyProcessed(t *testing.T) {
	db := setupWithdrawalTestDB(t)

	user := &model.User{Id: 200, Username: "testuser_processed", Phone: "13800138200"}
	db.Create(user)

	withdrawal := &model.Withdrawal{
		ID:            200,
		UserID:        200,
		Amount:        100,
		Status:        "approved",
		BankName:      "ICBC",
		BankAccount:   "6222021234567890",
		AccountName:   "张三",
		ApprovedAt:     func() *time.Time { t := time.Now(); return &t }(),
	}
	db.Create(withdrawal)

	svcCtx := &svc.ServiceContext{DB: db}
	logic := NewApproveWithdrawalLogic(context.Background(), svcCtx)

	req := &types.WithdrawalApproveReq{Status: "approved"}
	resp, err := logic.ApproveWithdrawal(200, req, 1)

	assert.Error(t, err)
	assert.Nil(t, resp)
	assert.Contains(t, err.Error(), "withdrawal can only be approved when pending")
}

func TestApproveWithdrawal_WithApprovedAt(t *testing.T) {
	db := setupWithdrawalTestDB(t)

	user := &model.User{Id: 300, Username: "testuser_approvedat", Phone: "13800138300"}
	brand := &model.Brand{Id: 300, Name: "Test Brand"}
	distributor := &model.Distributor{Id: 300, UserId: 300, BrandId: 300}
	db.Create(user)
	db.Create(brand)
	db.Create(distributor)

	withdrawal := &model.Withdrawal{
		ID:            300,
		UserID:        300,
		BrandId:       300,
		DistributorId: 300,
		Amount:        100,
		Status:        "pending",
		BankName:      "ICBC",
		BankAccount:   "6222021234567890",
		AccountName:   "张三",
	}
	db.Create(withdrawal)

	svcCtx := &svc.ServiceContext{DB: db}
	logic := NewApproveWithdrawalLogic(context.Background(), svcCtx)

	req := &types.WithdrawalApproveReq{Status: "approved"}
	resp, err := logic.ApproveWithdrawal(300, req, 1)

	assert.NoError(t, err)
	assert.NotNil(t, resp)
	assert.NotEmpty(t, resp.ApprovedAt)
}

func TestGetWithdrawals_WithBrandIdFilter(t *testing.T) {
	db := setupWithdrawalTestDB(t)

	user := &model.User{Id: 400, Username: "testuser_brand", Phone: "13800138400"}
	brand := &model.Brand{Id: 400, Name: "Test Brand"}
	brand2 := &model.Brand{Id: 401, Name: "Test Brand 2"}
	distributor := &model.Distributor{Id: 400, UserId: 400, BrandId: 400}
	balance := &model.UserBalance{UserId: 400, Balance: 500}

	db.Create(user)
	db.Create(brand)
	db.Create(brand2)
	db.Create(distributor)
	db.Create(balance)

	withdrawal1 := &model.Withdrawal{
		ID:            400,
		UserID:        400,
		BrandId:       400,
		DistributorId: 400,
		Amount:        100,
		Status:        "pending",
		BankName:      "ICBC",
		BankAccount:   "6222021234567890",
		AccountName:   "张三",
		CreatedAt:     time.Now(),
	}
	withdrawal2 := &model.Withdrawal{
		ID:            401,
		UserID:        400,
		BrandId:       401,
		DistributorId: 400,
		Amount:        200,
		Status:        "pending",
		BankName:      "CCB",
		BankAccount:   "6222021234567891",
		AccountName:   "李四",
		CreatedAt:     time.Now().Add(-1 * time.Hour),
	}
	db.Create(withdrawal1)
	db.Create(withdrawal2)

	svcCtx := &svc.ServiceContext{DB: db}
	logic := NewGetWithdrawalsLogic(context.Background(), svcCtx)

	req := &types.WithdrawalListReq{
		Page:     1,
		PageSize: 10,
		BrandId:   400,
	}
	resp, err := logic.GetWithdrawals(req)

	assert.NoError(t, err)
	assert.NotNil(t, resp)
	assert.Equal(t, int64(1), resp.Total)
}

func TestGetWithdrawals_WithStatusFilter(t *testing.T) {
	db := setupWithdrawalTestDB(t)

	user := &model.User{Id: 500, Username: "testuser_status", Phone: "13800138500"}
	brand := &model.Brand{Id: 500, Name: "Test Brand"}
	distributor := &model.Distributor{Id: 500, UserId: 500, BrandId: 500}
	balance := &model.UserBalance{UserId: 500, Balance: 500}

	db.Create(user)
	db.Create(brand)
	db.Create(distributor)
	db.Create(balance)

	withdrawal1 := &model.Withdrawal{
		ID:            500,
		UserID:        500,
		BrandId:       500,
		DistributorId: 500,
		Amount:        100,
		Status:        "pending",
		BankName:      "ICBC",
		BankAccount:   "6222021234567890",
		AccountName:   "张三",
		CreatedAt:     time.Now(),
	}
	withdrawal2 := &model.Withdrawal{
		ID:            501,
		UserID:        500,
		BrandId:       500,
		DistributorId: 500,
		Amount:        200,
		Status:        "approved",
		BankName:      "CCB",
		BankAccount:   "6222021234567891",
		AccountName:   "李四",
		CreatedAt:     time.Now().Add(-1 * time.Hour),
	}
	db.Create(withdrawal1)
	db.Create(withdrawal2)

	svcCtx := &svc.ServiceContext{DB: db}
	logic := NewGetWithdrawalsLogic(context.Background(), svcCtx)

	req := &types.WithdrawalListReq{
		Page:     1,
		PageSize: 10,
		Status:   "pending",
	}
	resp, err := logic.GetWithdrawals(req)

	assert.NoError(t, err)
	assert.NotNil(t, resp)
	// Should only find withdrawal1 (status=pending)
	assert.Equal(t, int64(1), resp.Total)
}

func TestGetWithdrawals_WithUserIdFilter(t *testing.T) {
	db := setupWithdrawalTestDB(t)

	user1 := &model.User{Id: 600, Username: "testuser_filter1", Phone: "13800138600"}
	user2 := &model.User{Id: 601, Username: "testuser_filter2", Phone: "13800138601"}
	brand := &model.Brand{Id: 600, Name: "Test Brand"}
	distributor := &model.Distributor{Id: 600, UserId: 600, BrandId: 600}
	balance1 := &model.UserBalance{UserId: 600, Balance: 500}
	balance2 := &model.UserBalance{UserId: 601, Balance: 500}

	db.Create(user1)
	db.Create(user2)
	db.Create(brand)
	db.Create(distributor)
	db.Create(balance1)
	db.Create(balance2)

	withdrawal1 := &model.Withdrawal{
		ID:            600,
		UserID:        600,
		BrandId:       600,
		DistributorId: 600,
		Amount:        100,
		Status:        "pending",
		BankName:      "ICBC",
		BankAccount:   "6222021234567890",
		AccountName:   "张三",
		CreatedAt:     time.Now(),
	}
	withdrawal2 := &model.Withdrawal{
		ID:            601,
		UserID:        601,
		BrandId:       600,
		DistributorId: 600,
		Amount:        200,
		Status:        "pending",
		BankName:      "CCB",
		BankAccount:   "6222021234567891",
		AccountName:   "李四",
		CreatedAt:     time.Now().Add(-1 * time.Hour),
	}
	db.Create(withdrawal1)
	db.Create(withdrawal2)

	svcCtx := &svc.ServiceContext{DB: db}
	logic := NewGetWithdrawalsLogic(context.Background(), svcCtx)

	req := &types.WithdrawalListReq{
		Page:     1,
		PageSize: 10,
		UserId:   600,
	}
	resp, err := logic.GetWithdrawals(req)

	assert.NoError(t, err)
	assert.NotNil(t, resp)
	// Should only find withdrawal1 (UserId=600)
	assert.Equal(t, int64(1), resp.Total)
}

