// Code generated by goctl. DO NOT EDIT.
package role

import (
	"context"
	"testing"

	"dmh/api/internal/svc"
	"dmh/api/internal/types"
	"dmh/model"

	"github.com/stretchr/testify/assert"
	"gorm.io/driver/sqlite"
	"gorm.io/gorm"
)

func setupRoleTestDB() *gorm.DB {
	db, _ := gorm.Open(sqlite.Open(":memory:"), &gorm.Config{})
	db.AutoMigrate(&model.Role{}, &model.Permission{}, &model.RolePermission{}, &model.UserRole{}, &model.UserBrand{}, &model.User{}, &model.Brand{})
	return db
}

func TestGetRolesLogic(t *testing.T) {
	db := setupRoleTestDB()

	role := &model.Role{
		ID:          1,
		Name:        "平台管理员",
		Code:        "platform_admin",
		Description: "平台管理员角色",
	}
	permission := &model.Permission{
		ID:          1,
		Name:        "查看活动",
		Code:        "campaign:read",
		Resource:    "campaign",
		Action:      "read",
		Description: "查看活动权限",
	}
	db.Create(role)
	db.Create(permission)

	rolePerm := &model.RolePermission{
		RoleID:       1,
		PermissionID: 1,
	}
	db.Create(rolePerm)

	svcCtx := &svc.ServiceContext{DB: db}
	logic := NewGetRolesLogic(context.Background(), svcCtx)

	resp, err := logic.GetRoles()

	assert.NoError(t, err)
	assert.NotNil(t, resp)
	assert.Len(t, resp, 1)
	assert.Equal(t, "平台管理员", resp[0].Name)
	assert.Equal(t, "platform_admin", resp[0].Code)
	assert.Len(t, resp[0].Permissions, 1)
	assert.Contains(t, resp[0].Permissions, "campaign:read")
}

func TestGetPermissionsLogic(t *testing.T) {
	db := setupRoleTestDB()

	permission := &model.Permission{
		ID:          1,
		Name:        "查看活动",
		Code:        "campaign:read",
		Resource:    "campaign",
		Action:      "read",
		Description: "查看活动权限",
	}
	db.Create(permission)

	svcCtx := &svc.ServiceContext{DB: db}
	logic := NewGetPermissionsLogic(context.Background(), svcCtx)

	resp, err := logic.GetPermissions()

	assert.NoError(t, err)
	assert.NotNil(t, resp)
	assert.Len(t, resp, 1)
	assert.Equal(t, "查看活动", resp[0].Name)
	assert.Equal(t, "campaign:read", resp[0].Code)
}

func TestGetUserPermissionsLogic(t *testing.T) {
	db := setupRoleTestDB()

	user := &model.User{
		Id:       1,
		Username: "testuser",
		Phone:    "13800138000",
		Role:     "participant",
	}
	role := &model.Role{
		ID:   1,
		Name: "平台管理员",
		Code: "platform_admin",
	}
	permission := &model.Permission{
		ID:       1,
		Name:     "查看活动",
		Code:     "campaign:read",
		Resource: "campaign",
		Action:   "read",
	}
	brand := &model.Brand{
		Id:   1,
		Name: "Test Brand",
	}
	db.Create(user)
	db.Create(role)
	db.Create(permission)
	db.Create(brand)

	userRole := &model.UserRole{
		UserID: 1,
		RoleID: 1,
	}
	db.Create(userRole)

	rolePerm := &model.RolePermission{
		RoleID:       1,
		PermissionID: 1,
	}
	db.Create(rolePerm)

	userBrand := &model.UserBrand{
		UserId:  1,
		BrandId: 1,
	}
	db.Create(userBrand)

	svcCtx := &svc.ServiceContext{DB: db}
	logic := NewGetUserPermissionsLogic(context.Background(), svcCtx)

	resp, err := logic.GetUserPermissions(1)

	assert.NoError(t, err)
	assert.NotNil(t, resp)
	assert.Equal(t, int64(1), resp.UserId)
	assert.Contains(t, resp.Roles, "platform_admin")
	assert.Contains(t, resp.Permissions, "campaign:read")
	assert.Contains(t, resp.BrandIds, int64(1))
}

func TestConfigRolePermissionsLogic(t *testing.T) {
	db := setupRoleTestDB()

	role := &model.Role{
		ID:   1,
		Name: "平台管理员",
		Code: "platform_admin",
	}
	permission1 := &model.Permission{
		ID:       1,
		Name:     "查看活动",
		Code:     "campaign:read",
		Resource: "campaign",
		Action:   "read",
	}
	permission2 := &model.Permission{
		ID:       2,
		Name:     "创建活动",
		Code:     "campaign:create",
		Resource: "campaign",
		Action:   "create",
	}
	db.Create(role)
	db.Create(permission1)
	db.Create(permission2)

	svcCtx := &svc.ServiceContext{DB: db}
	logic := NewConfigRolePermissionsLogic(context.Background(), svcCtx)

	req := &types.RolePermissionReq{
		RoleId:        1,
		PermissionIds: []int64{1, 2},
	}

	resp, err := logic.ConfigRolePermissions(req)

	assert.NoError(t, err)
	assert.NotNil(t, resp)
	assert.Equal(t, "Role permissions configured successfully", resp.Message)

	var count int64
	db.Model(&model.RolePermission{}).Where("role_id = ?", 1).Count(&count)
	assert.Equal(t, int64(2), count)
}
