// Code generated by goctl. DO NOT EDIT.
package poster

import (
	"context"
	"testing"

	"dmh/api/internal/svc"
	"dmh/api/internal/types"
	"dmh/model"

	"github.com/stretchr/testify/assert"
	"gorm.io/driver/sqlite"
	"gorm.io/gorm"
)

func setupPosterTestDB() *gorm.DB {
	db, _ := gorm.Open(sqlite.Open(":memory:"), &gorm.Config{})
	db.AutoMigrate(&model.PosterTemplateConfig{}, &model.PosterRecord{}, &model.Campaign{}, &model.Distributor{}, &model.User{})
	return db
}

func TestGetPosterTemplatesLogic(t *testing.T) {
	db := setupPosterTestDB()

	template := &model.PosterTemplateConfig{
		Id:           1,
		Name:         "活动模板1",
		PreviewImage: "/preview/image1.jpg",
		Config:       model.PosterTemplateConfigData{},
		Status:       "active",
	}
	db.Create(template)

	svcCtx := &svc.ServiceContext{DB: db}
	logic := NewGetPosterTemplatesLogic(context.Background(), svcCtx)

	req := &types.GetPosterTemplatesReq{
		Page:     1,
		PageSize: 10,
		Status:   "active",
		Keyword:  "活动",
	}

	resp, err := logic.GetPosterTemplates(req)

	assert.NoError(t, err)
	assert.NotNil(t, resp)
	assert.GreaterOrEqual(t, resp.Total, int64(1))
	assert.Len(t, resp.Templates, 1)
	assert.Equal(t, "活动模板1", resp.Templates[0].Name)
}

func TestGenerateCampaignPosterLogic(t *testing.T) {
	db := setupPosterTestDB()

	campaign := &model.Campaign{
		Id:               1,
		Name:             "测试活动",
		Description:      "这是一个测试活动",
		PosterTemplateId: 1,
	}
	template := &model.PosterTemplateConfig{
		Id:           1,
		Name:         "默认模板",
		PreviewImage: "/preview/image.jpg",
		Status:       "active",
	}
	db.Create(campaign)
	db.Create(template)

	svcCtx := &svc.ServiceContext{DB: db}
	logic := NewGenerateCampaignPosterLogic(context.Background(), svcCtx)

	req := &types.GeneratePosterReq{
		Id:         1,
		TemplateId: 1,
	}

	resp, err := logic.GenerateCampaignPoster(req)

	assert.NoError(t, err)
	assert.NotNil(t, resp)
	assert.NotEmpty(t, resp.PosterUrl)
	assert.Greater(t, resp.GenerationTime, 0)

	var record model.PosterRecord
	db.Where("record_type = ? AND campaign_id = ?", "campaign", 1).First(&record)
	assert.Equal(t, "campaign", record.RecordType)
	assert.Equal(t, int64(1), record.CampaignID)
	assert.Equal(t, "success", record.Status)
}

func TestGenerateDistributorPosterLogic(t *testing.T) {
	db := setupPosterTestDB()

	user := &model.User{
		Id:       1,
		Username: "testuser",
		Phone:    "13800138000",
	}
	distributor := &model.Distributor{
		Id:     1,
		UserId: 1,
		Level:  1,
		Status: "normal",
	}
	template := &model.PosterTemplateConfig{
		Id:     1,
		Name:   "默认模板",
		Status: "active",
	}
	db.Create(user)
	db.Create(distributor)
	db.Create(template)

	svcCtx := &svc.ServiceContext{DB: db}
	logic := NewGenerateDistributorPosterLogic(context.Background(), svcCtx)

	req := &types.GeneratePosterReq{
		TemplateId: 1,
	}

	resp, err := logic.GenerateDistributorPoster(req, 1)

	assert.NoError(t, err)
	assert.NotNil(t, resp)
	assert.NotEmpty(t, resp.PosterUrl)
	assert.Greater(t, resp.GenerationTime, 0)

	var record model.PosterRecord
	db.Where("record_type = ? AND distributor_id = ?", "distributor", 1).First(&record)
	assert.Equal(t, "distributor", record.RecordType)
	assert.Equal(t, int64(1), record.DistributorID)
	assert.Equal(t, "success", record.Status)
}

func TestGetPosterRecordsLogic(t *testing.T) {
	db := setupPosterTestDB()

	record1 := &model.PosterRecord{
		ID:             1,
		RecordType:     "campaign",
		CampaignID:     1,
		DistributorID:  0,
		TemplateName:   "模板1",
		PosterUrl:      "/poster1.jpg",
		GenerationTime: 1000,
		DownloadCount:  5,
		ShareCount:     3,
		Status:         "active",
	}
	record2 := &model.PosterRecord{
		ID:             2,
		RecordType:     "distributor",
		CampaignID:     0,
		DistributorID:  1,
		TemplateName:   "模板2",
		PosterUrl:      "/poster2.jpg",
		GenerationTime: 1500,
		DownloadCount:  10,
		ShareCount:     6,
		Status:         "active",
	}
	db.Create(record1)
	db.Create(record2)

	svcCtx := &svc.ServiceContext{DB: db}
	logic := NewGetPosterRecordsLogic(context.Background(), svcCtx)

	resp, err := logic.GetPosterRecords()

	assert.NoError(t, err)
	assert.NotNil(t, resp)
	assert.Equal(t, int64(2), resp.Total)
	assert.Len(t, resp.Records, 2)
}
