// Code generated by goctl. DO NOT EDIT.
package poster

import (
	"context"
	"testing"
	"time"

	"dmh/api/internal/handler/testutil"
	"dmh/api/internal/svc"
	"dmh/api/internal/types"
	"dmh/model"

	"github.com/stretchr/testify/assert"
	"gorm.io/gorm"
)

func setupPosterTestDB(t *testing.T) *gorm.DB {
	t.Helper()
	db := testutil.SetupGormTestDB(t)
	db.AutoMigrate(&model.PosterTemplateConfig{}, &model.PosterRecord{}, &model.Campaign{}, &model.Distributor{}, &model.User{})
	testutil.ClearTables(db, "poster_records", "poster_template_configs", "distributors", "campaigns", "users")
	return db
}

func TestGetPosterTemplatesLogic(t *testing.T) {
	db := setupPosterTestDB(t)

	template := &model.PosterTemplateConfig{
		Id:           1,
		Name:         "活动模板1",
		PreviewImage: "/preview/image1.jpg",
		Config:       model.PosterTemplateConfigData{},
		Status:       "active",
	}
	db.Create(template)

	svcCtx := &svc.ServiceContext{DB: db}
	logic := NewGetPosterTemplatesLogic(context.Background(), svcCtx)

	req := &types.GetPosterTemplatesReq{
		Page:     1,
		PageSize: 10,
		Status:   "active",
		Keyword:  "活动",
	}

	resp, err := logic.GetPosterTemplates(req)

	assert.NoError(t, err)
	assert.NotNil(t, resp)
	assert.GreaterOrEqual(t, resp.Total, int64(1))
	assert.Len(t, resp.Templates, 1)
	assert.Equal(t, "活动模板1", resp.Templates[0].Name)
}

func TestGenerateCampaignPosterLogic(t *testing.T) {
	db := setupPosterTestDB(t)

	campaign := &model.Campaign{
		Id:               1,
		Name:             "测试活动",
		Description:      "这是一个测试活动",
		PosterTemplateId: 1,
		StartTime:        time.Now().Add(-1 * time.Hour),
		EndTime:          time.Now().Add(24 * time.Hour),
		Status:           "active",
		BrandId:          1,
		RewardRule:       10,
	}
	template := &model.PosterTemplateConfig{
		Id:           1,
		Name:         "默认模板",
		PreviewImage: "/preview/image.jpg",
		Status:       "active",
	}
	db.Create(campaign)
	db.Create(template)

	svcCtx := &svc.ServiceContext{DB: db}
	logic := NewGenerateCampaignPosterLogic(context.Background(), svcCtx)

	req := &types.GeneratePosterReq{
		Id:         1,
		TemplateId: 1,
	}

	resp, err := logic.GenerateCampaignPoster(req)

	assert.NoError(t, err)
	assert.NotNil(t, resp)
	assert.NotEmpty(t, resp.PosterUrl)
	assert.Greater(t, resp.GenerationTime, 0)

	var record model.PosterRecord
	db.Where("record_type = ? AND campaign_id = ?", "campaign", 1).First(&record)
	assert.Equal(t, "campaign", record.RecordType)
	assert.Equal(t, int64(1), record.CampaignID)
	assert.Equal(t, "success", record.Status)
}

func TestGenerateDistributorPosterLogic(t *testing.T) {
	db := setupPosterTestDB(t)

	user := &model.User{
		Id:       1,
		Username: "testuser",
		Phone:    "13800138000",
	}
	brand := &model.Brand{Id: 1, Name: "Brand1", Status: "active"}
	distributor := &model.Distributor{
		Id:      1,
		UserId:  1,
		BrandId: 1,
		Level:   1,
		Status:  "active",
	}
	template := &model.PosterTemplateConfig{
		Id:     1,
		Name:   "默认模板",
		Status: "active",
	}
	db.Create(user)
	db.Create(brand)
	db.Create(distributor)
	db.Create(template)

	svcCtx := &svc.ServiceContext{DB: db}
	logic := NewGenerateDistributorPosterLogic(context.Background(), svcCtx)

	req := &types.GeneratePosterReq{
		TemplateId: 1,
	}

	resp, err := logic.GenerateDistributorPoster(req, 1)

	assert.NoError(t, err)
	assert.NotNil(t, resp)
	assert.NotEmpty(t, resp.PosterUrl)
	assert.Greater(t, resp.GenerationTime, 0)

	var record model.PosterRecord
	db.Where("record_type = ? AND distributor_id = ?", "distributor", 1).First(&record)
	assert.Equal(t, "distributor", record.RecordType)
	assert.Equal(t, int64(1), record.DistributorID)
	assert.Equal(t, "success", record.Status)
}

func TestGetPosterRecordsLogic(t *testing.T) {
	db := setupPosterTestDB(t)

	record1 := &model.PosterRecord{
		ID:             1,
		RecordType:     "campaign",
		CampaignID:     1,
		DistributorID:  0,
		TemplateName:   "模板1",
		PosterUrl:      "/poster1.jpg",
		GenerationTime: 1000,
		DownloadCount:  5,
		ShareCount:     3,
		Status:         "active",
	}
	record2 := &model.PosterRecord{
		ID:             2,
		RecordType:     "distributor",
		CampaignID:     0,
		DistributorID:  1,
		TemplateName:   "模板2",
		PosterUrl:      "/poster2.jpg",
		GenerationTime: 1500,
		DownloadCount:  10,
		ShareCount:     6,
		Status:         "active",
	}
	db.Create(record1)
	db.Create(record2)

	svcCtx := &svc.ServiceContext{DB: db}
	logic := NewGetPosterRecordsLogic(context.Background(), svcCtx)

	resp, err := logic.GetPosterRecords()

	assert.NoError(t, err)
	assert.NotNil(t, resp)
	assert.Equal(t, int64(2), resp.Total)
	assert.Len(t, resp.Records, 2)
}

// Error path tests

func TestGenerateCampaignPosterLogic_CampaignNotFound(t *testing.T) {
	db := setupPosterTestDB(t)

	svcCtx := &svc.ServiceContext{DB: db}
	logic := NewGenerateCampaignPosterLogic(context.Background(), svcCtx)

	req := &types.GeneratePosterReq{
		Id:         999, // Non-existent campaign
		TemplateId: 1,
	}

	resp, err := logic.GenerateCampaignPoster(req)

	assert.Error(t, err)
	assert.Nil(t, resp)
	assert.Contains(t, err.Error(), "Campaign not found")
}

func TestGenerateCampaignPosterLogic_TemplateNotFound(t *testing.T) {
	db := setupPosterTestDB(t)

	campaign := &model.Campaign{
		Id:               1,
		Name:             "测试活动",
		Description:      "这是一个测试活动",
		PosterTemplateId: 999, // Non-existent template
		StartTime:        time.Now().Add(-1 * time.Hour),
		EndTime:          time.Now().Add(24 * time.Hour),
		Status:           "active",
		BrandId:          1,
		RewardRule:       10,
	}
	db.Create(campaign)

	svcCtx := &svc.ServiceContext{DB: db}
	logic := NewGenerateCampaignPosterLogic(context.Background(), svcCtx)

	req := &types.GeneratePosterReq{
		Id:         1,
		TemplateId: 0, // Will use campaign's PosterTemplateId (999)
	}

	resp, err := logic.GenerateCampaignPoster(req)

	assert.Error(t, err)
	assert.Nil(t, resp)
	assert.Contains(t, err.Error(), "Poster template not found")
}

func TestGenerateDistributorPosterLogic_DistributorNotFound(t *testing.T) {
	db := setupPosterTestDB(t)

	svcCtx := &svc.ServiceContext{DB: db}
	logic := NewGenerateDistributorPosterLogic(context.Background(), svcCtx)

	req := &types.GeneratePosterReq{
		TemplateId: 1,
	}

	resp, err := logic.GenerateDistributorPoster(req, 999) // Non-existent distributor

	assert.Error(t, err)
	assert.Nil(t, resp)
	assert.Contains(t, err.Error(), "Distributor not found")
}

func TestGetPosterTemplatesLogic_NoFilters(t *testing.T) {
	db := setupPosterTestDB(t)

	template := &model.PosterTemplateConfig{
		Id:           1,
		Name:         "活动模板1",
		PreviewImage: "/preview/image1.jpg",
		Config:       model.PosterTemplateConfigData{},
		Status:       "active",
	}
	db.Create(template)

	svcCtx := &svc.ServiceContext{DB: db}
	logic := NewGetPosterTemplatesLogic(context.Background(), svcCtx)

	req := &types.GetPosterTemplatesReq{
		Page:     0, // No pagination
		PageSize: 0,
		Status:   "", // No status filter
		Keyword:  "", // No keyword filter
	}

	resp, err := logic.GetPosterTemplates(req)

	assert.NoError(t, err)
	assert.NotNil(t, resp)
	assert.GreaterOrEqual(t, resp.Total, int64(1))
	assert.Len(t, resp.Templates, 1)
}

func TestGetPosterRecordsLogic_WithGeneratedBy(t *testing.T) {
	db := setupPosterTestDB(t)

	generatedBy := int64(123)
	record := &model.PosterRecord{
		ID:             1,
		RecordType:     "campaign",
		CampaignID:     1,
		DistributorID:  0,
		TemplateName:   "模板1",
		PosterUrl:      "/poster1.jpg",
		GenerationTime: 1000,
		DownloadCount:  5,
		ShareCount:     3,
		Status:         "active",
		GeneratedBy:    &generatedBy,
	}
	db.Create(record)

	svcCtx := &svc.ServiceContext{DB: db}
	logic := NewGetPosterRecordsLogic(context.Background(), svcCtx)

	resp, err := logic.GetPosterRecords()

	assert.NoError(t, err)
	assert.NotNil(t, resp)
	assert.Equal(t, int64(1), resp.Total)
	assert.Len(t, resp.Records, 1)
	assert.Equal(t, int64(123), resp.Records[0].GeneratedBy)
}
