// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2

package types

type AdminCreateUserReq struct {
	Username string  `json:"username"`
	Password string  `json:"password"`
	Phone    string  `json:"phone"`
	Email    string  `json:"email,optional"`
	RealName string  `json:"realName,optional"`
	Role     string  `json:"role"`              // platform_admin, participant
	BrandIds []int64 `json:"brandIds,optional"` // 品牌管理员的品牌ID列表
}

type AdminGetUsersReq struct {
	Page     int64  `json:"page,optional" form:"page,optional"`
	PageSize int64  `json:"pageSize,optional" form:"pageSize,optional"`
	Role     string `json:"role,optional" form:"role,optional"`
	Status   string `json:"status,optional" form:"status,optional"`
	Keyword  string `json:"keyword,optional" form:"keyword,optional"`
}

type AdminResetPasswordReq struct {
	NewPassword string `json:"newPassword"`
}

type AdminUpdateUserReq struct {
	RealName string  `json:"realName,optional"`
	Email    string  `json:"email,optional"`
	Role     string  `json:"role,optional"`
	Status   string  `json:"status,optional"` // active, disabled, locked
	BrandIds []int64 `json:"brandIds,optional"`
}

type AdminUserListResp struct {
	Total int64          `json:"total"`
	Users []UserInfoResp `json:"users"`
}

type AuditLogListResp struct {
	Total int64          `json:"total"`
	Logs  []AuditLogResp `json:"logs"`
}

type AuditLogResp struct {
	Id         int64  `json:"id"`
	UserId     int64  `json:"userId,optional"`
	Username   string `json:"username"`
	Action     string `json:"action"`
	Resource   string `json:"resource"`
	ResourceId string `json:"resourceId"`
	Details    string `json:"details"`
	ClientIp   string `json:"clientIp"`
	UserAgent  string `json:"userAgent"`
	Status     string `json:"status"`
	ErrorMsg   string `json:"errorMsg"`
	CreatedAt  string `json:"createdAt"`
}

type BalanceResp struct {
	UserId      int64   `json:"userId"`
	Balance     float64 `json:"balance"`
	TotalReward float64 `json:"totalReward"`
}

type BindEmailReq struct {
	Email string `json:"email"`
	Code  string `json:"code"`
}

type BindPhoneReq struct {
	Phone string `json:"phone"`
	Code  string `json:"code"`
}

type BrandAdminRelationReq struct {
	UserId   int64   `json:"userId"`
	BrandIds []int64 `json:"brandIds"`
}

type BrandAssetListResp struct {
	Total  int64            `json:"total"`
	Assets []BrandAssetResp `json:"assets"`
}

type BrandAssetReq struct {
	Name        string `json:"name"`
	Type        string `json:"type"` // image/video/document
	Category    string `json:"category,optional"`
	Tags        string `json:"tags,optional"`
	FileUrl     string `json:"fileUrl"`
	FileSize    int64  `json:"fileSize"`
	Description string `json:"description,optional"`
}

type BrandAssetResp struct {
	Id          int64  `json:"id"`
	BrandId     int64  `json:"brandId"`
	Name        string `json:"name"`
	Type        string `json:"type"`
	Category    string `json:"category"`
	Tags        string `json:"tags"`
	FileUrl     string `json:"fileUrl"`
	FileSize    int64  `json:"fileSize"`
	Description string `json:"description"`
	CreatedAt   string `json:"createdAt"`
	UpdatedAt   string `json:"updatedAt"`
}

type BrandListResp struct {
	Total  int64       `json:"total"`
	Brands []BrandResp `json:"brands"`
}

type BrandResp struct {
	Id          int64  `json:"id"`
	Name        string `json:"name"`
	Logo        string `json:"logo"`
	Description string `json:"description"`
	Status      string `json:"status"`
	CreatedAt   string `json:"createdAt"`
	UpdatedAt   string `json:"updatedAt"`
}

type BrandStatsResp struct {
	BrandId          int64   `json:"brandId"`
	TotalCampaigns   int64   `json:"totalCampaigns"`
	ActiveCampaigns  int64   `json:"activeCampaigns"`
	TotalOrders      int64   `json:"totalOrders"`
	TotalRevenue     float64 `json:"totalRevenue"`
	TotalRewards     float64 `json:"totalRewards"`
	ParticipantCount int64   `json:"participantCount"`
	ConversionRate   float64 `json:"conversionRate"`
	LastUpdated      string  `json:"lastUpdated"`
}

type CampaignListResp struct {
	Total     int64          `json:"total"`
	Campaigns []CampaignResp `json:"campaigns"`
}

type CampaignResp struct {
	Id          int64       `json:"id"`
	BrandId     int64       `json:"brandId"`
	BrandName   string      `json:"brandName,optional"`
	Name        string      `json:"name"`
	Description string      `json:"description"`
	FormFields  []FormField `json:"formFields"`
	RewardRule  float64     `json:"rewardRule"`
	StartTime   string      `json:"startTime"`
	EndTime     string      `json:"endTime"`
	Status      string      `json:"status"`
	CreatedAt   string      `json:"createdAt"`
}

type ChangePasswordReq struct {
	OldPassword string `json:"oldPassword"`
	NewPassword string `json:"newPassword"`
}

type CommonResp struct {
	Message string `json:"message"`
}

type CreateBrandReq struct {
	Name        string `json:"name"`
	Logo        string `json:"logo,optional"`
	Description string `json:"description,optional"`
}

type CreateCampaignReq struct {
	BrandId     int64       `json:"brandId"`
	Name        string      `json:"name"`
	Description string      `json:"description"`
	FormFields  []FormField `json:"formFields"` // 动态表单字段
	RewardRule  float64     `json:"rewardRule"` // 奖励规则（金额）
	StartTime   string      `json:"startTime"`
	EndTime     string      `json:"endTime"`
}

type CreateMenuReq struct {
	Name     string `json:"name"`
	Code     string `json:"code"`
	Path     string `json:"path"`
	Icon     string `json:"icon,optional"`
	ParentId int64  `json:"parentId,optional"`
	Sort     int    `json:"sort"`
	Type     string `json:"type"`     // menu/button
	Platform string `json:"platform"` // admin/h5
}

type CreateOrderReq struct {
	CampaignId int64             `json:"campaignId"`
	Phone      string            `json:"phone"`
	FormData   map[string]string `json:"formData"`
	ReferrerId int64             `json:"referrerId,optional"` // 推荐人ID
}

type ForceLogoutReq struct {
	Reason string `json:"reason,optional"`
}

type FormField struct {
	Type        string   `json:"type"`                 // 字段类型: text, phone, select
	Name        string   `json:"name"`                 // 字段名称（英文）
	Label       string   `json:"label"`                // 字段标签（中文）
	Required    bool     `json:"required"`             // 是否必填
	Placeholder string   `json:"placeholder,optional"` // 占位符
	Options     []string `json:"options,optional"`     // 选项列表（仅select类型）
}

type GetCampaignsReq struct {
	Page     int64  `json:"page,optional" form:"page,optional"`
	PageSize int64  `json:"pageSize,optional" form:"pageSize,optional"`
	Status   string `json:"status,optional" form:"status,optional"`
	Keyword  string `json:"keyword,optional" form:"keyword,optional"`
}

type HandleSecurityEventReq struct {
	Note string `json:"note,optional"`
}

type LoginAttemptListResp struct {
	Total    int64              `json:"total"`
	Attempts []LoginAttemptResp `json:"attempts"`
}

type LoginAttemptResp struct {
	Id         int64  `json:"id"`
	UserId     int64  `json:"userId,optional"`
	Username   string `json:"username"`
	ClientIp   string `json:"clientIp"`
	UserAgent  string `json:"userAgent"`
	Success    bool   `json:"success"`
	FailReason string `json:"failReason"`
	CreatedAt  string `json:"createdAt"`
}

type LoginReq struct {
	Username string `json:"username"`
	Password string `json:"password"`
}

type LoginResp struct {
	Token    string   `json:"token"`
	UserId   int64    `json:"userId"`
	Username string   `json:"username"`
	Phone    string   `json:"phone"`
	RealName string   `json:"realName"`
	Roles    []string `json:"roles"`
	BrandIds []int64  `json:"brandIds,optional"` // 品牌管理员的品牌ID列表
}

type MenuResp struct {
	Id        int64      `json:"id"`
	Name      string     `json:"name"`
	Code      string     `json:"code"`
	Path      string     `json:"path"`
	Icon      string     `json:"icon,optional"`
	ParentId  int64      `json:"parentId,optional"`
	Sort      int        `json:"sort"`
	Type      string     `json:"type"`     // menu/button
	Platform  string     `json:"platform"` // admin/h5
	Status    string     `json:"status"`
	Children  []MenuResp `json:"children,optional"`
	CreatedAt string     `json:"createdAt"`
}

type OrderResp struct {
	Id         int64             `json:"id"`
	CampaignId int64             `json:"campaignId"`
	Phone      string            `json:"phone"`
	FormData   map[string]string `json:"formData"`
	ReferrerId int64             `json:"referrerId"`
	Status     string            `json:"status"`
	Amount     float64           `json:"amount"`
	CreatedAt  string            `json:"createdAt"`
}

type PageConfigReq struct {
	Components []map[string]interface{} `json:"components"`
	Theme      map[string]interface{}   `json:"theme"`
}

type PageConfigResp struct {
	Id         int64                    `json:"id"`
	CampaignId int64                    `json:"campaignId"`
	Components []map[string]interface{} `json:"components"`
	Theme      map[string]interface{}   `json:"theme"`
	CreatedAt  string                   `json:"createdAt"`
	UpdatedAt  string                   `json:"updatedAt"`
}

type PasswordPolicyResp struct {
	Id                    int64  `json:"id"`
	MinLength             int    `json:"minLength"`
	RequireUppercase      bool   `json:"requireUppercase"`
	RequireLowercase      bool   `json:"requireLowercase"`
	RequireNumbers        bool   `json:"requireNumbers"`
	RequireSpecialChars   bool   `json:"requireSpecialChars"`
	MaxAge                int    `json:"maxAge"`
	HistoryCount          int    `json:"historyCount"`
	MaxLoginAttempts      int    `json:"maxLoginAttempts"`
	LockoutDuration       int    `json:"lockoutDuration"`
	SessionTimeout        int    `json:"sessionTimeout"`
	MaxConcurrentSessions int    `json:"maxConcurrentSessions"`
	CreatedAt             string `json:"createdAt"`
	UpdatedAt             string `json:"updatedAt"`
}

type PasswordStrengthResp struct {
	Score   int    `json:"score"`
	Level   string `json:"level"`
	Message string `json:"message"`
}

type PaymentCallbackReq struct {
	OrderId   int64   `json:"orderId"`
	PayStatus string  `json:"payStatus"`
	Amount    float64 `json:"amount"`
	TradeNo   string  `json:"tradeNo"`
}

type PermissionResp struct {
	Id          int64  `json:"id"`
	Name        string `json:"name"`
	Code        string `json:"code"`
	Resource    string `json:"resource"`
	Action      string `json:"action"`
	Description string `json:"description"`
}

type RefreshTokenReq struct {
	Token string `json:"token"`
}

type RefreshTokenResp struct {
	Token string `json:"token"`
}

type RegisterReq struct {
	Username string `json:"username"`
	Password string `json:"password"`
	Phone    string `json:"phone"`
	Email    string `json:"email,optional"`
	RealName string `json:"realName,optional"`
}

type RetrySyncResp struct {
	OrderId int64  `json:"orderId"`
	Message string `json:"message"`
	TaskId  string `json:"taskId"`
}

type RewardResp struct {
	Id        int64   `json:"id"`
	UserId    int64   `json:"userId"`
	OrderId   int64   `json:"orderId"`
	Amount    float64 `json:"amount"`
	Status    string  `json:"status"`
	CreatedAt string  `json:"createdAt"`
}

type RoleMenuReq struct {
	RoleId  int64   `json:"roleId"`
	MenuIds []int64 `json:"menuIds"`
}

type RolePermissionReq struct {
	RoleId        int64   `json:"roleId"`
	PermissionIds []int64 `json:"permissionIds"`
}

type RoleResp struct {
	Id          int64    `json:"id"`
	Name        string   `json:"name"`
	Code        string   `json:"code"`
	Description string   `json:"description"`
	Permissions []string `json:"permissions,optional"`
	CreatedAt   string   `json:"createdAt"`
}

type SecurityEventListResp struct {
	Total  int64               `json:"total"`
	Events []SecurityEventResp `json:"events"`
}

type SecurityEventResp struct {
	Id          int64  `json:"id"`
	EventType   string `json:"eventType"`
	Severity    string `json:"severity"`
	UserId      int64  `json:"userId,optional"`
	Username    string `json:"username"`
	ClientIp    string `json:"clientIp"`
	UserAgent   string `json:"userAgent"`
	Description string `json:"description"`
	Details     string `json:"details"`
	Handled     bool   `json:"handled"`
	HandledBy   int64  `json:"handledBy,optional"`
	HandledAt   string `json:"handledAt,optional"`
	CreatedAt   string `json:"createdAt"`
}

type SendCodeReq struct {
	Target string `json:"target"` // 手机号或邮箱
	Type   string `json:"type"`   // phone/email
}

type SyncHealthResp struct {
	Status   string                 `json:"status"`
	Database map[string]interface{} `json:"database"`
	Queue    map[string]interface{} `json:"queue"`
}

type SyncStatsResp struct {
	TotalSyncs   int64   `json:"totalSyncs"`
	SuccessSyncs int64   `json:"successSyncs"`
	FailedSyncs  int64   `json:"failedSyncs"`
	SuccessRate  float64 `json:"successRate"`
	AvgTime      string  `json:"avgTime"`
}

type SyncStatusResp struct {
	OrderId    int64  `json:"orderId"`
	SyncStatus string `json:"syncStatus"`
	SyncTime   string `json:"syncTime,optional"`
	Attempts   int    `json:"attempts"`
	ErrorMsg   string `json:"errorMsg,optional"`
}

type UpdateBrandReq struct {
	Name        string `json:"name,optional"`
	Logo        string `json:"logo,optional"`
	Description string `json:"description,optional"`
	Status      string `json:"status,optional"` // active/disabled
}

type UpdateMenuReq struct {
	Name     string `json:"name,optional"`
	Code     string `json:"code,optional"`
	Path     string `json:"path,optional"`
	Icon     string `json:"icon,optional"`
	ParentId int64  `json:"parentId,optional"`
	Sort     int    `json:"sort,optional"`
	Type     string `json:"type,optional"`
	Platform string `json:"platform,optional"`
	Status   string `json:"status,optional"`
}

type UpdatePasswordPolicyReq struct {
	MinLength             int  `json:"minLength,optional"`
	RequireUppercase      bool `json:"requireUppercase,optional"`
	RequireLowercase      bool `json:"requireLowercase,optional"`
	RequireNumbers        bool `json:"requireNumbers,optional"`
	RequireSpecialChars   bool `json:"requireSpecialChars,optional"`
	MaxAge                int  `json:"maxAge,optional"`
	HistoryCount          int  `json:"historyCount,optional"`
	MaxLoginAttempts      int  `json:"maxLoginAttempts,optional"`
	LockoutDuration       int  `json:"lockoutDuration,optional"`
	SessionTimeout        int  `json:"sessionTimeout,optional"`
	MaxConcurrentSessions int  `json:"maxConcurrentSessions,optional"`
}

type UpdateProfileReq struct {
	RealName string `json:"realName"`
}

type UserInfoResp struct {
	Id        int64    `json:"id"`
	Username  string   `json:"username"`
	Phone     string   `json:"phone"`
	Email     string   `json:"email"`
	RealName  string   `json:"realName"`
	Avatar    string   `json:"avatar"`
	Status    string   `json:"status"`
	Roles     []string `json:"roles"`
	BrandIds  []int64  `json:"brandIds,optional"`
	CreatedAt string   `json:"createdAt"`
}

type UserMenuResp struct {
	UserId   int64      `json:"userId"`
	Platform string     `json:"platform"`
	Menus    []MenuResp `json:"menus"`
}

type UserPermissionResp struct {
	UserId      int64    `json:"userId"`
	Roles       []string `json:"roles"`
	Permissions []string `json:"permissions"`
	BrandIds    []int64  `json:"brandIds,optional"`
}

type UserSessionListResp struct {
	Total    int64             `json:"total"`
	Sessions []UserSessionResp `json:"sessions"`
}

type UserSessionResp struct {
	Id           string `json:"id"`
	UserId       int64  `json:"userId"`
	ClientIp     string `json:"clientIp"`
	UserAgent    string `json:"userAgent"`
	LoginAt      string `json:"loginAt"`
	LastActiveAt string `json:"lastActiveAt"`
	ExpiresAt    string `json:"expiresAt"`
	Status       string `json:"status"`
	CreatedAt    string `json:"createdAt"`
}

type WithdrawalApplyReq struct {
	Amount      float64 `json:"amount"`
	BankName    string  `json:"bankName"`
	BankAccount string  `json:"bankAccount"`
	AccountName string  `json:"accountName"`
}

type WithdrawalApproveReq struct {
	Status string `json:"status"` // approved/rejected
	Remark string `json:"remark,optional"`
}

type WithdrawalListResp struct {
	Total       int64            `json:"total"`
	Withdrawals []WithdrawalResp `json:"withdrawals"`
}

type WithdrawalResp struct {
	Id          int64   `json:"id"`
	UserId      int64   `json:"userId"`
	Username    string  `json:"username,optional"`
	RealName    string  `json:"realName,optional"`
	Amount      float64 `json:"amount"`
	BankName    string  `json:"bankName"`
	BankAccount string  `json:"bankAccount"`
	AccountName string  `json:"accountName"`
	Status      string  `json:"status"`
	Remark      string  `json:"remark,optional"`
	ApprovedBy  int64   `json:"approvedBy,optional"`
	ApprovedAt  string  `json:"approvedAt,optional"`
	CreatedAt   string  `json:"createdAt"`
}
