// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2

package types

type AdminCreateUserReq struct {
	Username string  `json:"username"`
	Password string  `json:"password"`
	Phone    string  `json:"phone"`
	Email    string  `json:"email,optional"`
	RealName string  `json:"realName,optional"`
	Role     string  `json:"role"`              // platform_admin, participant
	BrandIds []int64 `json:"brandIds,optional"` // 品牌管理员的品牌ID列表
}

type AdminGetUsersReq struct {
	Page     int64  `json:"page,optional" form:"page,optional"`
	PageSize int64  `json:"pageSize,optional" form:"pageSize,optional"`
	Role     string `json:"role,optional" form:"role,optional"`
	Status   string `json:"status,optional" form:"status,optional"`
	Keyword  string `json:"keyword,optional" form:"keyword,optional"`
}

type AdminResetPasswordReq struct {
	NewPassword string `json:"newPassword"`
}

type AdminUpdateUserReq struct {
	RealName string  `json:"realName,optional"`
	Email    string  `json:"email,optional"`
	Role     string  `json:"role,optional"`
	Status   string  `json:"status,optional"` // active, disabled, locked
	BrandIds []int64 `json:"brandIds,optional"`
}

type AdminUserListResp struct {
	Total int64          `json:"total"`
	Users []UserInfoResp `json:"users"`
}

type AuditLogListResp struct {
	Total int64          `json:"total"`
	Logs  []AuditLogResp `json:"logs"`
}

type AuditLogResp struct {
	Id         int64  `json:"id"`
	UserId     int64  `json:"userId,optional"`
	Username   string `json:"username"`
	Action     string `json:"action"`
	Resource   string `json:"resource"`
	ResourceId string `json:"resourceId"`
	Details    string `json:"details"`
	ClientIp   string `json:"clientIp"`
	UserAgent  string `json:"userAgent"`
	Status     string `json:"status"`
	ErrorMsg   string `json:"errorMsg"`
	CreatedAt  string `json:"createdAt"`
}

type BalanceResp struct {
	UserId      int64   `json:"userId"`
	Balance     float64 `json:"balance"`
	TotalReward float64 `json:"totalReward"`
}

type BindEmailReq struct {
	Email string `json:"email"`
	Code  string `json:"code"`
}

type BindPhoneReq struct {
	Phone string `json:"phone"`
	Code  string `json:"code"`
}

type BrandAdminRelationReq struct {
	UserId   int64   `json:"userId"`
	BrandIds []int64 `json:"brandIds"`
}

type BrandAssetListResp struct {
	Total  int64            `json:"total"`
	Assets []BrandAssetResp `json:"assets"`
}

type BrandAssetReq struct {
	Name        string `json:"name"`
	Type        string `json:"type"` // image/video/document
	Category    string `json:"category,optional"`
	Tags        string `json:"tags,optional"`
	FileUrl     string `json:"fileUrl"`
	FileSize    int64  `json:"fileSize"`
	Description string `json:"description,optional"`
}

type BrandAssetResp struct {
	Id          int64  `json:"id"`
	BrandId     int64  `json:"brandId"`
	Name        string `json:"name"`
	Type        string `json:"type"`
	Category    string `json:"category"`
	Tags        string `json:"tags"`
	FileUrl     string `json:"fileUrl"`
	FileSize    int64  `json:"fileSize"`
	Description string `json:"description"`
	CreatedAt   string `json:"createdAt"`
	UpdatedAt   string `json:"updatedAt"`
}

type BrandListResp struct {
	Total  int64       `json:"total"`
	Brands []BrandResp `json:"brands"`
}

type BrandResp struct {
	Id          int64  `json:"id"`
	Name        string `json:"name"`
	Logo        string `json:"logo"`
	Description string `json:"description"`
	Status      string `json:"status"`
	CreatedAt   string `json:"createdAt"`
	UpdatedAt   string `json:"updatedAt"`
}

type BrandStatsResp struct {
	BrandId          int64   `json:"brandId"`
	TotalCampaigns   int64   `json:"totalCampaigns"`
	ActiveCampaigns  int64   `json:"activeCampaigns"`
	TotalOrders      int64   `json:"totalOrders"`
	TotalRevenue     float64 `json:"totalRevenue"`
	TotalRewards     float64 `json:"totalRewards"`
	ParticipantCount int64   `json:"participantCount"`
	ConversionRate   float64 `json:"conversionRate"`
	LastUpdated      string  `json:"lastUpdated"`
}

type CampaignListResp struct {
	Total     int64          `json:"total"`
	Campaigns []CampaignResp `json:"campaigns"`
}

type CampaignResp struct {
	Id                  int64                        `json:"id"`
	BrandId             int64                        `json:"brandId"`
	BrandName           string                       `json:"brandName,optional"`
	Name                string                       `json:"name"`
	Description         string                       `json:"description"`
	FormFields          []FormField                  `json:"formFields"`
	RewardRule          float64                      `json:"rewardRule"`
	StartTime           string                       `json:"startTime"`
	EndTime             string                       `json:"endTime"`
	Status              string                       `json:"status"`
	EnableDistribution  bool                         `json:"enableDistribution"`
	DistributionLevel   int                          `json:"distributionLevel"`
	DistributionRewards []DistributorLevelRewardResp `json:"distributionRewards"`
	CreatedAt           string                       `json:"createdAt"`
}

type ChangePasswordReq struct {
	OldPassword string `json:"oldPassword"`
	NewPassword string `json:"newPassword"`
}

type CommonResp struct {
	Message string `json:"message"`
}

type CreateBrandReq struct {
	Name        string `json:"name"`
	Logo        string `json:"logo,optional"`
	Description string `json:"description,optional"`
}

type CreateCampaignReq struct {
	BrandId             int64                           `json:"brandId"`
	Name                string                          `json:"name"`
	Description         string                          `json:"description"`
	FormFields          []FormField                     `json:"formFields"` // 动态表单字段
	RewardRule          float64                         `json:"rewardRule"` // 奖励规则（金额）
	StartTime           string                          `json:"startTime"`
	EndTime             string                          `json:"endTime"`
	EnableDistribution  bool                            `json:"enableDistribution,optional"`  // 是否启用分销
	DistributionLevel   int                             `json:"distributionLevel,optional"`   // 分销层级(1/2/3)
	DistributionRewards []CampaignDistributionRewardReq `json:"distributionRewards,optional"` // 各级奖励比例
}

// CampaignDistributionRewardReq 活动分销奖励配置请求
type CampaignDistributionRewardReq struct {
	Level            int64   `json:"level"`            // 1/2/3
	RewardPercentage float64 `json:"rewardPercentage"` // 百分比，如 5.5 表示 5.5%
}

type CreateMenuReq struct {
	Name     string `json:"name"`
	Code     string `json:"code"`
	Path     string `json:"path"`
	Icon     string `json:"icon,optional"`
	ParentId int64  `json:"parentId,optional"`
	Sort     int    `json:"sort"`
	Type     string `json:"type"`     // menu/button
	Platform string `json:"platform"` // admin/h5
}

type CreateOrderReq struct {
	CampaignId int64             `json:"campaignId"`
	UnionID    string            `json:"unionid,optional"` // 微信 unionid
	Phone      string            `json:"phone"`
	FormData   map[string]string `json:"formData"`
	ReferrerId int64             `json:"referrerId,optional"` // 推荐人ID
	Amount     float64           `json:"amount,optional"`     // 订单金额
}

type ForceLogoutReq struct {
	Reason string `json:"reason,optional"`
}

type FormField struct {
	Type        string   `json:"type"`                 // 字段类型: text, phone, select
	Name        string   `json:"name"`                 // 字段名称（英文）
	Label       string   `json:"label"`                // 字段标签（中文）
	Required    bool     `json:"required"`             // 是否必填
	Placeholder string   `json:"placeholder,optional"` // 占位符
	Options     []string `json:"options,optional"`     // 选项列表（仅select类型）
}

type GetCampaignsReq struct {
	Page     int64  `json:"page,optional" form:"page,optional"`
	PageSize int64  `json:"pageSize,optional" form:"pageSize,optional"`
	Status   string `json:"status,optional" form:"status,optional"`
	Keyword  string `json:"keyword,optional" form:"keyword,optional"`
}

type HandleSecurityEventReq struct {
	Note string `json:"note,optional"`
}

type LoginAttemptListResp struct {
	Total    int64              `json:"total"`
	Attempts []LoginAttemptResp `json:"attempts"`
}

type LoginAttemptResp struct {
	Id         int64  `json:"id"`
	UserId     int64  `json:"userId,optional"`
	Username   string `json:"username"`
	ClientIp   string `json:"clientIp"`
	UserAgent  string `json:"userAgent"`
	Success    bool   `json:"success"`
	FailReason string `json:"failReason"`
	CreatedAt  string `json:"createdAt"`
}

type LoginReq struct {
	Username string `json:"username"`
	Password string `json:"password"`
}

type LoginResp struct {
	Token    string   `json:"token"`
	UserId   int64    `json:"userId"`
	Username string   `json:"username"`
	Phone    string   `json:"phone"`
	RealName string   `json:"realName"`
	Roles    []string `json:"roles"`
	BrandIds []int64  `json:"brandIds,optional"` // 品牌管理员的品牌ID列表
}

type MenuResp struct {
	Id        int64      `json:"id"`
	Name      string     `json:"name"`
	Code      string     `json:"code"`
	Path      string     `json:"path"`
	Icon      string     `json:"icon,optional"`
	ParentId  int64      `json:"parentId,optional"`
	Sort      int        `json:"sort"`
	Type      string     `json:"type"`     // menu/button
	Platform  string     `json:"platform"` // admin/h5
	Status    string     `json:"status"`
	Children  []MenuResp `json:"children,optional"`
	CreatedAt string     `json:"createdAt"`
}

type OrderResp struct {
	Id           int64             `json:"id"`
	CampaignId   int64             `json:"campaignId"`
	CampaignName string            `json:"campaignName,optional"`
	Phone        string            `json:"phone"`
	FormData     map[string]string `json:"formData"`
	ReferrerId   int64             `json:"referrerId"`
	Status       string            `json:"status"`
	Amount       float64           `json:"amount"`
	CreatedAt    string            `json:"createdAt"`
}

type PageConfigReq struct {
	Components []map[string]interface{} `json:"components"`
	Theme      map[string]interface{}   `json:"theme"`
}

type PageConfigResp struct {
	Id         int64                    `json:"id"`
	CampaignId int64                    `json:"campaignId"`
	Components []map[string]interface{} `json:"components"`
	Theme      map[string]interface{}   `json:"theme"`
	CreatedAt  string                   `json:"createdAt"`
	UpdatedAt  string                   `json:"updatedAt"`
}

type PasswordPolicyResp struct {
	Id                    int64  `json:"id"`
	MinLength             int    `json:"minLength"`
	RequireUppercase      bool   `json:"requireUppercase"`
	RequireLowercase      bool   `json:"requireLowercase"`
	RequireNumbers        bool   `json:"requireNumbers"`
	RequireSpecialChars   bool   `json:"requireSpecialChars"`
	MaxAge                int    `json:"maxAge"`
	HistoryCount          int    `json:"historyCount"`
	MaxLoginAttempts      int    `json:"maxLoginAttempts"`
	LockoutDuration       int    `json:"lockoutDuration"`
	SessionTimeout        int    `json:"sessionTimeout"`
	MaxConcurrentSessions int    `json:"maxConcurrentSessions"`
	CreatedAt             string `json:"createdAt"`
	UpdatedAt             string `json:"updatedAt"`
}

type PasswordStrengthResp struct {
	Score   int    `json:"score"`
	Level   string `json:"level"`
	Message string `json:"message"`
}

type PaymentCallbackReq struct {
	OrderId   int64   `json:"orderId"`
	PayStatus string  `json:"payStatus"`
	Amount    float64 `json:"amount"`
	TradeNo   string  `json:"tradeNo"`
}

type PermissionResp struct {
	Id          int64  `json:"id"`
	Name        string `json:"name"`
	Code        string `json:"code"`
	Resource    string `json:"resource"`
	Action      string `json:"action"`
	Description string `json:"description"`
}

type RefreshTokenReq struct {
	Token string `json:"token"`
}

type RefreshTokenResp struct {
	Token string `json:"token"`
}

type RegisterReq struct {
	Username string `json:"username"`
	Password string `json:"password"`
	Phone    string `json:"phone"`
	Email    string `json:"email,optional"`
	RealName string `json:"realName,optional"`
}

type RetrySyncResp struct {
	OrderId int64  `json:"orderId"`
	Message string `json:"message"`
	TaskId  string `json:"taskId"`
}

type RewardResp struct {
	Id        int64   `json:"id"`
	UserId    int64   `json:"userId"`
	OrderId   int64   `json:"orderId"`
	Amount    float64 `json:"amount"`
	Status    string  `json:"status"`
	CreatedAt string  `json:"createdAt"`
}

type RoleMenuReq struct {
	RoleId  int64   `json:"roleId"`
	MenuIds []int64 `json:"menuIds"`
}

type RolePermissionReq struct {
	RoleId        int64   `json:"roleId"`
	PermissionIds []int64 `json:"permissionIds"`
}

type RoleResp struct {
	Id          int64    `json:"id"`
	Name        string   `json:"name"`
	Code        string   `json:"code"`
	Description string   `json:"description"`
	Permissions []string `json:"permissions,optional"`
	CreatedAt   string   `json:"createdAt"`
}

type SecurityEventListResp struct {
	Total  int64               `json:"total"`
	Events []SecurityEventResp `json:"events"`
}

type SecurityEventResp struct {
	Id          int64  `json:"id"`
	EventType   string `json:"eventType"`
	Severity    string `json:"severity"`
	UserId      int64  `json:"userId,optional"`
	Username    string `json:"username"`
	ClientIp    string `json:"clientIp"`
	UserAgent   string `json:"userAgent"`
	Description string `json:"description"`
	Details     string `json:"details"`
	Handled     bool   `json:"handled"`
	HandledBy   int64  `json:"handledBy,optional"`
	HandledAt   string `json:"handledAt,optional"`
	CreatedAt   string `json:"createdAt"`
}

type SendCodeReq struct {
	Target string `json:"target"` // 手机号或邮箱
	Type   string `json:"type"`   // phone/email
}

type SyncHealthResp struct {
	Status   string                 `json:"status"`
	Database map[string]interface{} `json:"database"`
	Queue    map[string]interface{} `json:"queue"`
}

type HealthResp struct {
	Status    string `json:"status"`
	Database  string `json:"database"`
	Timestamp int64  `json:"timestamp"`
}

type SyncStatsResp struct {
	TotalSyncs   int64   `json:"totalSyncs"`
	SuccessSyncs int64   `json:"successSyncs"`
	FailedSyncs  int64   `json:"failedSyncs"`
	SuccessRate  float64 `json:"successRate"`
	AvgTime      string  `json:"avgTime"`
}

type SyncStatusResp struct {
	OrderId    int64  `json:"orderId"`
	SyncStatus string `json:"syncStatus"`
	SyncTime   string `json:"syncTime,optional"`
	Attempts   int    `json:"attempts"`
	ErrorMsg   string `json:"errorMsg,optional"`
}

type UpdateBrandReq struct {
	Name        string `json:"name,optional"`
	Logo        string `json:"logo,optional"`
	Description string `json:"description,optional"`
	Status      string `json:"status,optional"` // active/disabled
}

type UpdateMenuReq struct {
	Name     string `json:"name,optional"`
	Code     string `json:"code,optional"`
	Path     string `json:"path,optional"`
	Icon     string `json:"icon,optional"`
	ParentId int64  `json:"parentId,optional"`
	Sort     int    `json:"sort,optional"`
	Type     string `json:"type,optional"`
	Platform string `json:"platform,optional"`
	Status   string `json:"status,optional"`
}

type UpdatePasswordPolicyReq struct {
	MinLength             int  `json:"minLength,optional"`
	RequireUppercase      bool `json:"requireUppercase,optional"`
	RequireLowercase      bool `json:"requireLowercase,optional"`
	RequireNumbers        bool `json:"requireNumbers,optional"`
	RequireSpecialChars   bool `json:"requireSpecialChars,optional"`
	MaxAge                int  `json:"maxAge,optional"`
	HistoryCount          int  `json:"historyCount,optional"`
	MaxLoginAttempts      int  `json:"maxLoginAttempts,optional"`
	LockoutDuration       int  `json:"lockoutDuration,optional"`
	SessionTimeout        int  `json:"sessionTimeout,optional"`
	MaxConcurrentSessions int  `json:"maxConcurrentSessions,optional"`
}

type UpdateProfileReq struct {
	RealName string `json:"realName"`
}

type UserInfoResp struct {
	Id        int64    `json:"id"`
	Username  string   `json:"username"`
	Phone     string   `json:"phone"`
	Email     string   `json:"email"`
	RealName  string   `json:"realName"`
	Avatar    string   `json:"avatar"`
	Status    string   `json:"status"`
	Roles     []string `json:"roles"`
	BrandIds  []int64  `json:"brandIds,optional"`
	CreatedAt string   `json:"createdAt"`
}

type UserMenuResp struct {
	UserId   int64      `json:"userId"`
	Platform string     `json:"platform"`
	Menus    []MenuResp `json:"menus"`
}

type UserPermissionResp struct {
	UserId      int64    `json:"userId"`
	Roles       []string `json:"roles"`
	Permissions []string `json:"permissions"`
	BrandIds    []int64  `json:"brandIds,optional"`
}

type UserSessionListResp struct {
	Total    int64             `json:"total"`
	Sessions []UserSessionResp `json:"sessions"`
}

type UserSessionResp struct {
	Id           string `json:"id"`
	UserId       int64  `json:"userId"`
	ClientIp     string `json:"clientIp"`
	UserAgent    string `json:"userAgent"`
	LoginAt      string `json:"loginAt"`
	LastActiveAt string `json:"lastActiveAt"`
	ExpiresAt    string `json:"expiresAt"`
	Status       string `json:"status"`
	CreatedAt    string `json:"createdAt"`
}

type WithdrawalApplyReq struct {
	Amount      float64 `json:"amount"`
	BankName    string  `json:"bankName"`
	BankAccount string  `json:"bankAccount"`
	AccountName string  `json:"accountName"`
}

type WithdrawalApproveReq struct {
	Status string `json:"status"` // approved/rejected
	Remark string `json:"remark,optional"`
}

type WithdrawalListResp struct {
	Total       int64            `json:"total"`
	Withdrawals []WithdrawalResp `json:"withdrawals"`
}

type WithdrawalResp struct {
	Id          int64   `json:"id"`
	UserId      int64   `json:"userId"`
	Username    string  `json:"username,optional"`
	RealName    string  `json:"realName,optional"`
	Amount      float64 `json:"amount"`
	BankName    string  `json:"bankName"`
	BankAccount string  `json:"bankAccount"`
	AccountName string  `json:"accountName"`
	Status      string  `json:"status"`
	Remark      string  `json:"remark,optional"`
	ApprovedBy  int64   `json:"approvedBy,optional"`
	ApprovedAt  string  `json:"approvedAt,optional"`
	CreatedAt   string  `json:"createdAt"`
}

// Member related types

type GetMembersReq struct {
	Page      int64   `json:"page,optional" form:"page,optional"`
	PageSize  int64   `json:"pageSize,optional" form:"pageSize,optional"`
	BrandId   int64   `json:"brandId,optional" form:"brandId,optional"` // 品牌管理员筛选
	Keyword   string  `json:"keyword,optional" form:"keyword,optional"` // 搜索昵称/手机号/unionid
	Source    string  `json:"source,optional" form:"source,optional"`   // 来源渠道
	Status    string  `json:"status,optional" form:"status,optional"`
	TagIds    []int64 `json:"tagIds,optional" form:"tagIds,optional"`       // 标签筛选
	StartDate string  `json:"startDate,optional" form:"startDate,optional"` // 创建时间范围
	EndDate   string  `json:"endDate,optional" form:"endDate,optional"`
}

type MemberResp struct {
	Id                    int64             `json:"id"`
	UnionID               string            `json:"unionid"`
	Nickname              string            `json:"nickname"`
	Avatar                string            `json:"avatar"`
	Phone                 string            `json:"phone"`
	Gender                int               `json:"gender"`
	Source                string            `json:"source"`
	Status                string            `json:"status"`
	TotalOrders           int               `json:"totalOrders"`
	TotalPayment          float64           `json:"totalPayment"`
	TotalReward           float64           `json:"totalReward"`
	ParticipatedCampaigns int               `json:"participatedCampaigns"`
	FirstOrderAt          string            `json:"firstOrderAt,omitempty"`
	LastOrderAt           string            `json:"lastOrderAt,omitempty"`
	CreatedAt             string            `json:"createdAt"`
	Tags                  []MemberTagResp   `json:"tags,omitempty"`
	Brands                []MemberBrandResp `json:"brands,omitempty"`
	Orders                []OrderResp       `json:"orders,omitempty"`
}

type MemberListResp struct {
	Total   int64        `json:"total"`
	Members []MemberResp `json:"members"`
}

type MemberTagResp struct {
	Id          int64  `json:"id"`
	Name        string `json:"name"`
	Category    string `json:"category"`
	Color       string `json:"color"`
	Description string `json:"description"`
}

type MemberBrandResp struct {
	BrandId         int64  `json:"brandId"`
	BrandName       string `json:"brandName"`
	FirstCampaignId int64  `json:"firstCampaignId"`
	CreatedAt       string `json:"createdAt"`
}

type CreateMemberTagReq struct {
	Name        string `json:"name"`
	Category    string `json:"category,optional"`
	Color       string `json:"color,optional"`
	Description string `json:"description,optional"`
}

type UpdateMemberTagReq struct {
	Name        string `json:"name,optional"`
	Category    string `json:"category,optional"`
	Color       string `json:"color,optional"`
	Description string `json:"description,optional"`
}

type AddMemberTagsReq struct {
	MemberId int64   `json:"memberId"`
	TagIds   []int64 `json:"tagIds"`
}

type RemoveMemberTagsReq struct {
	MemberId int64   `json:"memberId"`
	TagIds   []int64 `json:"tagIds"`
}

type MemberMergeReq struct {
	SourceMemberId int64  `json:"sourceMemberId"` // 被合并的会员
	TargetMemberId int64  `json:"targetMemberId"` // 主会员（保留）
	Reason         string `json:"reason,optional"`
}

type MemberMergePreviewResp struct {
	SourceMember MemberResp `json:"sourceMember"`
	TargetMember MemberResp `json:"targetMember"`
	Conflicts    []string   `json:"conflicts,omitempty"` // 冲突信息
	CanMerge     bool       `json:"canMerge"`
}

type MemberMergeRequestResp struct {
	Id             int64  `json:"id"`
	SourceMemberId int64  `json:"sourceMemberId"`
	TargetMemberId int64  `json:"targetMemberId"`
	Status         string `json:"status"`
	Reason         string `json:"reason"`
	ConflictInfo   string `json:"conflictInfo"`
	CreatedBy      int64  `json:"createdBy"`
	CreatedByName  string `json:"createdByName"`
	ExecutedAt     string `json:"executedAt,omitempty"`
	ErrorMsg       string `json:"errorMsg,omitempty"`
	CreatedAt      string `json:"createdAt"`
}

type ExportRequestReq struct {
	BrandId int64  `json:"brandId"`
	Reason  string `json:"reason"`
	Filters string `json:"filters,optional"` // JSON 格式的筛选条件
}

type ExportRequestResp struct {
	Id              int64  `json:"id"`
	BrandId         int64  `json:"brandId"`
	BrandName       string `json:"brandName"`
	RequestedBy     int64  `json:"requestedBy"`
	RequestedByName string `json:"requestedByName"`
	Reason          string `json:"reason"`
	Filters         string `json:"filters"`
	Status          string `json:"status"`
	ApprovedBy      int64  `json:"approvedBy,omitempty"`
	ApprovedByName  string `json:"approvedByName,omitempty"`
	ApprovedAt      string `json:"approvedAt,omitempty"`
	RejectReason    string `json:"rejectReason,omitempty"`
	FileUrl         string `json:"fileUrl,omitempty"`
	RecordCount     int    `json:"recordCount"`
	CreatedAt       string `json:"createdAt"`
}

type ExportRequestListResp struct {
	Total    int64               `json:"total"`
	Requests []ExportRequestResp `json:"requests"`
}

type ApproveExportReq struct {
	Approve bool   `json:"approve"`         // true=批准, false=驳回
	Reason  string `json:"reason,optional"` // 驳回原因
}

type GetExportRequestsReq struct {
	Page     int64  `json:"page,optional" form:"page,optional"`
	PageSize int64  `json:"pageSize,optional" form:"pageSize,optional"`
	BrandId  int64  `json:"brandId,optional" form:"brandId,optional"`
	Status   string `json:"status,optional" form:"status,optional"`
}

// ============================================
// 分销商相关类型
// ============================================

// 分销商申请
type DistributorApplyReq struct {
	BrandId int64  `json:"brandId"`
	Reason  string `json:"reason"`
}

type DistributorApplicationResp struct {
	Id          int64  `json:"id"`
	UserId      int64  `json:"userId"`
	Username    string `json:"username,omitempty"`
	BrandId     int64  `json:"brandId"`
	BrandName   string `json:"brandName,omitempty"`
	Status      string `json:"status"`
	Reason      string `json:"reason"`
	ReviewedBy  int64  `json:"reviewedBy,omitempty"`
	Reviewer    string `json:"reviewer,omitempty"`
	ReviewedAt  string `json:"reviewedAt,omitempty"`
	ReviewNotes string `json:"reviewNotes,omitempty"`
	CreatedAt   string `json:"createdAt"`
}

type DistributorApplicationListResp struct {
	Total        int64                        `json:"total"`
	Applications []DistributorApplicationResp `json:"applications"`
}

// 分销商审批
type ApproveDistributorReq struct {
	Action string `json:"action"`          // approve/reject
	Level  int    `json:"level,optional"`  // 批准时设置的级别 1-3
	Reason string `json:"reason,optional"` // 拒绝原因或备注
}

// 分销商信息
type DistributorResp struct {
	Id                int64   `json:"id"`
	UserId            int64   `json:"userId"`
	Username          string  `json:"username,omitempty"`
	BrandId           int64   `json:"brandId"`
	BrandName         string  `json:"brandName,omitempty"`
	Level             int     `json:"level"`
	ParentId          int64   `json:"parentId,omitempty"`
	ParentName        string  `json:"parentName,omitempty"`
	Status            string  `json:"status"`
	TotalEarnings     float64 `json:"totalEarnings"`
	SubordinatesCount int     `json:"subordinatesCount"`
	ApprovedBy        int64   `json:"approvedBy,omitempty"`
	ApprovedAt        string  `json:"approvedAt,omitempty"`
	CreatedAt         string  `json:"createdAt"`
}

type DistributorListResp struct {
	Total        int64             `json:"total"`
	Distributors []DistributorResp `json:"distributors"`
}

type UpdateDistributorLevelReq struct {
	Level int `json:"level"` // 1-3
}

type UpdateDistributorStatusReq struct {
	Status string `json:"status"` // active/suspended
	Reason string `json:"reason,optional"`
}

// 分销商推广工具
type GenerateLinkReq struct {
	CampaignId int64 `json:"campaignId"`
}

type GenerateLinkResp struct {
	LinkId     int64  `json:"linkId"`
	Link       string `json:"link"`
	LinkCode   string `json:"linkCode"`
	QrcodeUrl  string `json:"qrcodeUrl,omitempty"`
	CampaignId int64  `json:"campaignId"`
}

type GetQrcodeResp struct {
	QrcodeUrl string `json:"qrcodeUrl"`
	LinkCode  string `json:"linkCode"`
}

// 分销商统计数据
type DistributorStatisticsResp struct {
	DistributorId     int64   `json:"distributorId"`
	TotalOrders       int64   `json:"totalOrders"`
	TotalEarnings     float64 `json:"totalEarnings"`
	TodayEarnings     float64 `json:"todayEarnings"`
	MonthEarnings     float64 `json:"monthEarnings"`
	SubordinatesCount int     `json:"subordinatesCount"`
	ClickCount        int     `json:"clickCount"`
	ConversionRate    float64 `json:"conversionRate"`
}

type DistributorRewardResp struct {
	Id           int64   `json:"id"`
	OrderId      int64   `json:"orderId"`
	Amount       float64 `json:"amount"`
	Level        int     `json:"level"`
	RewardRate   float64 `json:"rewardRate"`
	FromUserId   int64   `json:"fromUserId,omitempty"`
	FromUsername string  `json:"fromUsername,omitempty"`
	Status       string  `json:"status"`
	SettledAt    string  `json:"settledAt,omitempty"`
	CreatedAt    string  `json:"createdAt"`
}

type DistributorRewardListResp struct {
	Total   int64                   `json:"total"`
	Rewards []DistributorRewardResp `json:"rewards"`
}

type GetDistributorRewardsReq struct {
	Page      int64  `json:"page,optional" form:"page,optional"`
	PageSize  int64  `json:"pageSize,optional" form:"pageSize,optional"`
	Level     int    `json:"level,optional" form:"level,optional"`
	StartDate string `json:"startDate,optional" form:"startDate,optional"`
	EndDate   string `json:"endDate,optional" form:"endDate,optional"`
}

// 分销商下级列表
type SubordinateResp struct {
	Id            int64   `json:"id"`
	UserId        int64   `json:"userId"`
	Username      string  `json:"username,omitempty"`
	Level         int     `json:"level"`
	TotalOrders   int     `json:"totalOrders"`
	TotalEarnings float64 `json:"totalEarnings"`
	CreatedAt     string  `json:"createdAt"`
}

type SubordinateListResp struct {
	Total        int64             `json:"total"`
	Subordinates []SubordinateResp `json:"subordinates"`
}

// 品牌管理员审批申请列表查询
type GetDistributorApplicationsReq struct {
	Page     int64  `json:"page,optional" form:"page,optional"`
	PageSize int64  `json:"pageSize,optional" form:"pageSize,optional"`
	BrandId  int64  `json:"brandId,optional" form:"brandId,optional"`
	Status   string `json:"status,optional" form:"status,optional"`
}

// 分销商列表查询
type GetDistributorsReq struct {
	Page     int64  `json:"page,optional" form:"page,optional"`
	PageSize int64  `json:"pageSize,optional" form:"pageSize,optional"`
	BrandId  int64  `json:"brandId,optional" form:"brandId,optional"`
	Level    int    `json:"level,optional" form:"level,optional"`
	Status   string `json:"status,optional" form:"status,optional"`
	Keyword  string `json:"keyword,optional" form:"keyword,optional"`
}

// 分销商级别奖励配置
type DistributorLevelRewardResp struct {
	Id               int64   `json:"id"`
	BrandId          int64   `json:"brandId"`
	Level            int     `json:"level"`
	RewardPercentage float64 `json:"rewardPercentage"`
}

type DistributorLevelRewardsResp struct {
	BrandId int64                        `json:"brandId"`
	Rewards []DistributorLevelRewardResp `json:"rewards"`
}

type SetDistributorLevelRewardReq struct {
	Level            int64   `json:"level"`            // 1/2/3
	RewardPercentage float64 `json:"rewardPercentage"` // 百分比，如 5.5 表示 5.5%
}

type SetDistributorLevelRewardsReq struct {
	Rewards []SetDistributorLevelRewardReq `json:"rewards"`
}

// Path parameter types
type PathIDReq struct {
	ID int64 `path:"id"`
}

type PathBrandIDReq struct {
	BrandID int64 `path:"brandId"`
}

type PathLinkCodeReq struct {
	LinkCode string `path:"linkCode"`
}

type PathDistributorIDReq struct {
	DistributorID int64 `path:"id"`
}

type PathBrandIDApplicationIDReq struct {
	BrandID       int64 `path:"brandId"`
	ApplicationID int64 `path:"id"`
}

type PathBrandIDDistributorIDReq struct {
	BrandID       int64 `path:"brandId"`
	DistributorID int64 `path:"id"`
}

type PaginationReq struct {
	Page     int64 `form:"page,optional"`
	PageSize int64 `form:"pageSize,optional"`
}

type ApplyWithdrawalReq struct {
	Amount      float64 `json:"amount"`
	PayType     string  `json:"payType"`
	PayAccount  string  `json:"payAccount"`
	PayRealName string  `json:"payRealName"`
}

type ApproveWithdrawalReq struct {
	Notes string `json:"notes"`
}

type RejectWithdrawalReq struct {
	Reason string `json:"reason"`
}

type GetWithdrawalsReq struct {
	BrandId  int64  `json:"brandId,optional" form:"brandId,optional"`
	Status   string `json:"status,optional" form:"status,optional"`
	Page     int64  `form:"page,optional"`
	PageSize int64  `form:"pageSize,optional"`
}

type GeneratePosterReq struct {
	CampaignId int64 `json:"campaignId,optional"`
}

type GeneratePosterResp struct {
	PosterUrl  string `json:"posterUrl"`
	LinkCode   string `json:"linkCode,omitempty"`
	IsGeneric  bool   `json:"isGeneric"`
	CampaignId int64  `json:"campaignId,omitempty"`
}

type AutoUpgradeDistributorReq struct {
	UserId     int64   `json:"userId"`
	BrandId    int64   `json:"brandId"`
	OrderId    int64   `json:"orderId"`
	Amount     float64 `json:"amount"`
	ReferrerId int64   `json:"referrerId,optional"`
}

type AutoUpgradeDistributorResp struct {
	BecomeDistributor bool   `json:"becomeDistributor"`
	DistributorId     int64  `json:"distributorId,omitempty"`
	Message           string `json:"message"`
}

type CalculateMultiLevelRewardReq struct {
	OrderId    int64   `json:"orderId"`
	Amount     float64 `json:"amount"`
	ReferrerId int64   `json:"referrerId"`
	BrandId    int64   `json:"brandId"`
	CampaignId int64   `json:"campaignId"`
}

type CalculateMultiLevelRewardResp struct {
	Rewards []RewardDetail `json:"rewards"`
	Total   float64        `json:"total"`
}

type RewardDetail struct {
	DistributorId   int64   `json:"distributorId"`
	DistributorName string  `json:"distributorName,omitempty"`
	Level           int     `json:"level"`
	Amount          float64 `json:"amount"`
	RewardRate      float64 `json:"rewardRate"`
}

type GetGlobalStatsReq struct {
	StartDate string `json:"startDate,optional" form:"startDate,optional"`
	EndDate   string `json:"endDate,optional" form:"endDate,optional"`
}

type GlobalStatsResp struct {
	TotalDistributors  int64   `json:"totalDistributors"`
	ActiveDistributors int64   `json:"activeDistributors"`
	TotalRewards       float64 `json:"totalRewards"`
	TotalWithdrawals   float64 `json:"totalWithdrawals"`
	PendingWithdrawals int64   `json:"pendingWithdrawals"`
	TotalOrders        int64   `json:"totalOrders"`
	TotalRevenue       float64 `json:"totalRevenue"`
}

// 平台管理员全局查询类型
type GetPlatformDistributorsReq struct {
	Page     int64  `json:"page,optional" form:"page,optional"`
	PageSize int64  `json:"pageSize,optional" form:"pageSize,optional"`
	BrandId  int64  `json:"brandId,optional" form:"brandId,optional"`
	Level    int    `json:"level,optional" form:"level,optional"`
	Status   string `json:"status,optional" form:"status,optional"`
	Keyword  string `json:"keyword,optional" form:"keyword,optional"`
}

type GetPlatformRewardsReq struct {
	Page       int64  `json:"page,optional" form:"page,optional"`
	PageSize   int64  `json:"pageSize,optional" form:"pageSize,optional"`
	BrandId    int64  `json:"brandId,optional" form:"brandId,optional"`
	CampaignId int64  `json:"campaignId,optional" form:"campaignId,optional"`
	Status     string `json:"status,optional" form:"status,optional"`
	Keyword    string `json:"keyword,optional" form:"keyword,optional"`
	StartDate  string `json:"startDate,optional" form:"startDate,optional"`
	EndDate    string `json:"endDate,optional" form:"endDate,optional"`
}

type GetPlatformWithdrawalsReq struct {
	Page      int64  `json:"page,optional" form:"page,optional"`
	PageSize  int64  `json:"pageSize,optional" form:"pageSize,optional"`
	BrandId   int64  `json:"brandId,optional" form:"brandId,optional"`
	Status    string `json:"status,optional" form:"status,optional"`
	Keyword   string `json:"keyword,optional" form:"keyword,optional"`
	StartDate string `json:"startDate,optional" form:"startDate,optional"`
	EndDate   string `json:"endDate,optional" form:"endDate,optional"`
}

// 顾客相关类型
type GetCustomersReq struct {
	Page       int64  `json:"page,optional" form:"page,optional"`
	PageSize   int64  `json:"pageSize,optional" form:"pageSize,optional"`
	BrandId    int64  `json:"brandId,optional" form:"brandId,optional"`
	CampaignId int64  `json:"campaignId,optional" form:"campaignId,optional"`
	Keyword    string `json:"keyword,optional" form:"keyword,optional"`
	Status     string `json:"status,optional" form:"status,optional"`
}

type CustomerResp struct {
	Id           int64   `json:"id"`
	UserId       int64   `json:"userId"`
	Username     string  `json:"username"`
	Phone        string  `json:"phone"`
	BrandId      int64   `json:"brandId"`
	BrandName    string  `json:"brandName,omitempty"`
	CampaignId   int64   `json:"campaignId"`
	CampaignName string  `json:"campaignName,omitempty"`
	OrderCount   int64   `json:"orderCount"`
	TotalAmount  float64 `json:"totalAmount"`
	FirstOrderAt string  `json:"firstOrderAt,omitempty"`
	LastOrderAt  string  `json:"lastOrderAt,omitempty"`
	CreatedAt    string  `json:"createdAt"`
}

type CustomerListResp struct {
	Total     int64          `json:"total"`
	Customers []CustomerResp `json:"customers"`
}

// 品牌奖励详情类型
type GetBrandRewardsReq struct {
	Page       int64  `json:"page,optional" form:"page,optional"`
	PageSize   int64  `json:"pageSize,optional" form:"pageSize,optional"`
	BrandId    int64  `json:"brandId,optional" form:"brandId,optional"`
	CampaignId int64  `json:"campaignId,optional" form:"campaignId,optional"`
	Keyword    string `json:"keyword,optional" form:"keyword,optional"`
	Status     string `json:"status,optional" form:"status,optional"`
	StartDate  string `json:"startDate,optional" form:"startDate,optional"`
	EndDate    string `json:"endDate,optional" form:"endDate,optional"`
}

type BrandRewardResp struct {
	Id           int64   `json:"id"`
	UserId       int64   `json:"userId"`
	Username     string  `json:"username"`
	OrderId      int64   `json:"orderId"`
	CampaignId   int64   `json:"campaignId"`
	CampaignName string  `json:"campaignName,omitempty"`
	Amount       float64 `json:"amount"`
	Status       string  `json:"status"`
	SettledAt    string  `json:"settledAt,omitempty"`
	CreatedAt    string  `json:"createdAt"`
}

type BrandRewardListResp struct {
	Total   int64             `json:"total"`
	Rewards []BrandRewardResp `json:"rewards"`
}
