// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2

package types

type AdminCreateUserReq struct {
	Username string  `json:"username"`
	Password string  `json:"password"`
	Phone    string  `json:"phone"`
	Email    string  `json:"email,optional"`
	RealName string  `json:"realName,optional"`
	Role     string  `json:"role"`              // platform_admin, brand_admin, participant
	BrandIds []int64 `json:"brandIds,optional"` // 品牌管理员的品牌ID列表
}

type AdminGetUsersReq struct {
	Page     int64  `json:"page,optional" form:"page,optional"`
	PageSize int64  `json:"pageSize,optional" form:"pageSize,optional"`
	Role     string `json:"role,optional" form:"role,optional"`
	Status   string `json:"status,optional" form:"status,optional"`
	Keyword  string `json:"keyword,optional" form:"keyword,optional"`
}

type AdminResetPasswordReq struct {
	NewPassword string `json:"newPassword"`
}

type AdminUpdateUserReq struct {
	RealName string  `json:"realName,optional"`
	Email    string  `json:"email,optional"`
	Role     string  `json:"role,optional"`
	Status   string  `json:"status,optional"` // active, disabled, locked
	BrandIds []int64 `json:"brandIds,optional"`
}

type AdminUserListResp struct {
	Total int64          `json:"total"`
	Users []UserInfoResp `json:"users"`
}

type ApproveDistributorReq struct {
	Action string `json:"action"`          // approve/reject
	Level  int    `json:"level,optional"`  // 批准时设置的级别 1-3
	Reason string `json:"reason,optional"` // 拒绝原因或备注
}

type AuditLogListResp struct {
	Total int64          `json:"total"`
	Logs  []AuditLogResp `json:"logs"`
}

type AuditLogResp struct {
	Id         int64  `json:"id"`
	UserId     int64  `json:"userId,optional"`
	Username   string `json:"username"`
	Action     string `json:"action"`
	Resource   string `json:"resource"`
	ResourceId string `json:"resourceId"`
	Details    string `json:"details"`
	ClientIp   string `json:"clientIp"`
	UserAgent  string `json:"userAgent"`
	Status     string `json:"status"`
	ErrorMsg   string `json:"errorMsg"`
	CreatedAt  string `json:"createdAt"`
}

type BalanceResp struct {
	UserId      int64   `json:"userId"`
	Balance     float64 `json:"balance"`
	TotalReward float64 `json:"totalReward"`
}

type BindEmailReq struct {
	Email string `json:"email"`
	Code  string `json:"code"`
}

type BindPhoneReq struct {
	Phone string `json:"phone"`
	Code  string `json:"code"`
}

type BrandAdminRelationReq struct {
	UserId   int64   `json:"userId"`
	BrandIds []int64 `json:"brandIds"`
}

type BrandAssetListResp struct {
	Total  int64            `json:"total"`
	Assets []BrandAssetResp `json:"assets"`
}

type BrandAssetReq struct {
	Name        string `json:"name"`
	Type        string `json:"type"` // image/video/document
	Category    string `json:"category,optional"`
	Tags        string `json:"tags,optional"`
	FileUrl     string `json:"fileUrl"`
	FileSize    int64  `json:"fileSize"`
	Description string `json:"description,optional"`
}

type BrandAssetResp struct {
	Id          int64  `json:"id"`
	BrandId     int64  `json:"brandId"`
	Name        string `json:"name"`
	Type        string `json:"type"`
	Category    string `json:"category"`
	Tags        string `json:"tags"`
	FileUrl     string `json:"fileUrl"`
	FileSize    int64  `json:"fileSize"`
	Description string `json:"description"`
	CreatedAt   string `json:"createdAt"`
	UpdatedAt   string `json:"updatedAt"`
}

type BrandListResp struct {
	Total  int64       `json:"total"`
	Brands []BrandResp `json:"brands"`
}

type BrandResp struct {
	Id          int64  `json:"id"`
	Name        string `json:"name"`
	Logo        string `json:"logo"`
	Description string `json:"description"`
	Status      string `json:"status"`
	CreatedAt   string `json:"createdAt"`
	UpdatedAt   string `json:"updatedAt"`
}

type BrandStatsResp struct {
	BrandId          int64   `json:"brandId"`
	TotalCampaigns   int64   `json:"totalCampaigns"`
	ActiveCampaigns  int64   `json:"activeCampaigns"`
	TotalOrders      int64   `json:"totalOrders"`
	TotalRevenue     float64 `json:"totalRevenue"`
	TotalRewards     float64 `json:"totalRewards"`
	ParticipantCount int64   `json:"participantCount"`
	ConversionRate   float64 `json:"conversionRate"`
	LastUpdated      string  `json:"lastUpdated"`
}

type CampaignListResp struct {
	Total     int64          `json:"total"`
	Campaigns []CampaignResp `json:"campaigns"`
}

type GetPaymentQrcodeReq struct {
	Id int64 `path:"id"`
}

type GetCampaignReq struct {
	Id int64 `path:"id"`
}

type CampaignResp struct {
	Id          int64   `json:"id"`
	BrandId     int64   `json:"brandId"`
	Name        string  `json:"name"`
	Description string  `json:"description"`
	FormFields  string  `json:"formFields"`
	RewardRule  float64 `json:"rewardRule"`
	StartTime   string  `json:"startTime"`
	EndTime     string  `json:"endTime"`
	Status      string  `json:"status"`
	CreatedAt   string  `json:"createdAt"`
	UpdatedAt   string  `json:"updatedAt"`
}

type ChangePasswordReq struct {
	OldPassword string `json:"oldPassword"`
	NewPassword string `json:"newPassword"`
}

type CommonResp struct {
	Message string `json:"message"`
}

type CreateBrandReq struct {
	Name        string `json:"name"`
	Logo        string `json:"logo,optional"`
	Description string `json:"description,optional"`
}

type CreateCampaignReq struct {
	BrandId     int64       `json:"brandId"`
	Name        string      `json:"name"`
	Description string      `json:"description"`
	FormFields  []FormField `json:"formFields"` // 动态表单字段
	RewardRule  float64     `json:"rewardRule"` // 奖励规则（金额）
	StartTime   string      `json:"startTime"`
	EndTime     string      `json:"endTime"`
}

type CreateMenuReq struct {
	Name     string `json:"name"`
	Code     string `json:"code"`
	Path     string `json:"path"`
	Icon     string `json:"icon,optional"`
	ParentId int64  `json:"parentId,optional"`
	Sort     int    `json:"sort"`
	Type     string `json:"type"`     // menu/button
	Platform string `json:"platform"` // admin/h5
}

type CreateOrderReq struct {
	CampaignId int64             `json:"campaignId"`
	Phone      string            `json:"phone"`
	FormData   map[string]string `json:"formData"`
	ReferrerId int64             `json:"referrerId,optional"` // 推荐人ID
}

type DistributorApplicationListResp struct {
	Total        int64                        `json:"total"`
	Applications []DistributorApplicationResp `json:"applications"`
}

type DistributorApplicationResp struct {
	Id          int64  `json:"id"`
	UserId      int64  `json:"userId"`
	Username    string `json:"username,optional"`
	BrandId     int64  `json:"brandId"`
	BrandName   string `json:"brandName,optional"`
	Status      string `json:"status"`
	Reason      string `json:"reason"`
	ReviewedBy  int64  `json:"reviewedBy,optional"`
	Reviewer    string `json:"reviewer,optional"`
	ReviewedAt  string `json:"reviewedAt,optional"`
	ReviewNotes string `json:"reviewNotes,optional"`
	CreatedAt   string `json:"createdAt"`
}

type DistributorApplyReq struct {
	BrandId int64  `json:"brandId"`
	Reason  string `json:"reason"`
}

type DistributorLevelRewardResp struct {
	Id               int64   `json:"id"`
	BrandId          int64   `json:"brandId"`
	Level            int     `json:"level"`
	RewardPercentage float64 `json:"rewardPercentage"`
}

type DistributorLevelRewardsResp struct {
	BrandId int64                        `json:"brandId"`
	Rewards []DistributorLevelRewardResp `json:"rewards"`
}

type DistributorListResp struct {
	Total        int64             `json:"total"`
	Distributors []DistributorResp `json:"distributors"`
}

type DistributorResp struct {
	Id                int64   `json:"id"`
	UserId            int64   `json:"userId"`
	Username          string  `json:"username,optional"`
	BrandId           int64   `json:"brandId"`
	BrandName         string  `json:"brandName,optional"`
	Level             int     `json:"level"`
	ParentId          int64   `json:"parentId,optional"`
	ParentName        string  `json:"parentName,optional"`
	Status            string  `json:"status"`
	TotalEarnings     float64 `json:"totalEarnings"`
	SubordinatesCount int     `json:"subordinatesCount"`
	ApprovedBy        int64   `json:"approvedBy,optional"`
	ApprovedAt        string  `json:"approvedAt,optional"`
	CreatedAt         string  `json:"createdAt"`
}

type DistributorRewardListResp struct {
	Total   int64                   `json:"total"`
	Rewards []DistributorRewardResp `json:"rewards"`
}

type DistributorRewardResp struct {
	Id           int64   `json:"id"`
	OrderId      int64   `json:"orderId"`
	Amount       float64 `json:"amount"`
	Level        int     `json:"level"`
	RewardRate   float64 `json:"rewardRate"`
	FromUserId   int64   `json:"fromUserId,optional"`
	FromUsername string  `json:"fromUsername,optional"`
	Status       string  `json:"status"`
	SettledAt    string  `json:"settledAt,optional"`
	CreatedAt    string  `json:"createdAt"`
}

type DistributorStatisticsResp struct {
	DistributorId     int64   `json:"distributorId"`
	TotalOrders       int64   `json:"totalOrders"`
	TotalEarnings     float64 `json:"totalEarnings"`
	TodayEarnings     float64 `json:"todayEarnings"`
	MonthEarnings     float64 `json:"monthEarnings"`
	SubordinatesCount int     `json:"subordinatesCount"`
	ClickCount        int     `json:"clickCount"`
	ConversionRate    float64 `json:"conversionRate"`
}

type ForceLogoutReq struct {
	Reason string `json:"reason,optional"`
}

type FormField struct {
	Type        string               `json:"type"`                 // 字段类型: text, phone, email, address, textarea, select
	Name        string               `json:"name"`                 // 字段名称（英文）
	Label       string               `json:"label"`                // 字段标签（中文）
	Required    bool                 `json:"required"`             // 是否必填
	Placeholder string               `json:"placeholder,optional"` // 占位符
	Options     []string             `json:"options,optional"`     // 选项列表（仅select类型）
	Validation  *FormFieldValidation `json:"validation,optional"`  // 验证规则
}

type GenerateLinkReq struct {
	CampaignId int64 `json:"campaignId"`
}

type GenerateLinkResp struct {
	LinkId     int64  `json:"linkId"`
	Link       string `json:"link"`
	LinkCode   string `json:"linkCode"`
	QrcodeUrl  string `json:"qrcodeUrl,optional"`
	CampaignId int64  `json:"campaignId"`
}

type GeneratePosterReq struct {
	TemplateId int64  `json:"templateId"`
	Theme      string `json:"theme,optional"`
}

type GeneratePosterResp struct {
	PosterUrl      string `json:"posterUrl"`
	ThumbnailUrl   string `json:"thumbnailUrl,optional"`
	FileSize       string `json:"fileSize,optional"`
	GenerationTime int    `json:"generationTime,optional"`
}

type GetCampaignsReq struct {
	Page     int64  `json:"page,optional" form:"page,optional"`
	PageSize int64  `json:"pageSize,optional" form:"pageSize,optional"`
	Status   string `json:"status,optional" form:"status,optional"`
	Keyword  string `json:"keyword,optional" form:"keyword,optional"`
}

type GetDistributorApplicationsReq struct {
	Page     int64  `json:"page,optional" form:"page,optional"`
	PageSize int64  `json:"pageSize,optional" form:"pageSize,optional"`
	BrandId  int64  `json:"brandId,optional" form:"brandId,optional"`
	Status   string `json:"status,optional" form:"status,optional"`
}

type GetDistributorRewardsReq struct {
	Page      int64  `json:"page,optional" form:"page,optional"`
	PageSize  int64  `json:"pageSize,optional" form:"pageSize,optional"`
	Level     int    `json:"level,optional" form:"level,optional"`
	StartDate string `json:"startDate,optional" form:"startDate,optional"`
	EndDate   string `json:"endDate,optional" form:"endDate,optional"`
}

type GetDistributorsReq struct {
	Page     int64  `json:"page,optional" form:"page,optional"`
	PageSize int64  `json:"pageSize,optional" form:"pageSize,optional"`
	BrandId  int64  `json:"brandId,optional" form:"brandId,optional"`
	Level    int    `json:"level,optional" form:"level,optional"`
	Status   string `json:"status,optional" form:"status,optional"`
	Keyword  string `json:"keyword,optional" form:"keyword,optional"`
}

type GetPosterTemplatesReq struct {
	Page     int64  `json:"page,optional" form:"page,optional"`
	PageSize int64  `json:"pageSize,optional" form:"pageSize,optional"`
	Status   string `json:"status,optional" form:"status,optional"`
	Keyword  string `json:"keyword,optional" form:"keyword,optional"`
}

type GetQrcodeResp struct {
	QrcodeUrl string `json:"qrcodeUrl"`
	LinkCode  string `json:"linkCode"`
}

type HandleSecurityEventReq struct {
	Note string `json:"note,optional"`
}

type LoginAttemptListResp struct {
	Total    int64              `json:"total"`
	Attempts []LoginAttemptResp `json:"attempts"`
}

type LoginAttemptResp struct {
	Id         int64  `json:"id"`
	UserId     int64  `json:"userId,optional"`
	Username   string `json:"username"`
	ClientIp   string `json:"clientIp"`
	UserAgent  string `json:"userAgent"`
	Success    bool   `json:"success"`
	FailReason string `json:"failReason"`
	CreatedAt  string `json:"createdAt"`
}

type LoginReq struct {
	Username string `json:"username"`
	Password string `json:"password"`
}

type LoginResp struct {
	Token    string   `json:"token"`
	UserId   int64    `json:"userId"`
	Username string   `json:"username"`
	Phone    string   `json:"phone"`
	RealName string   `json:"realName"`
	Roles    []string `json:"roles"`
	BrandIds []int64  `json:"brandIds,optional"` // 品牌管理员的品牌ID列表
}

type MenuResp struct {
	Id        int64      `json:"id"`
	Name      string     `json:"name"`
	Code      string     `json:"code"`
	Path      string     `json:"path"`
	Icon      string     `json:"icon,optional"`
	ParentId  int64      `json:"parentId,optional"`
	Sort      int        `json:"sort"`
	Type      string     `json:"type"`     // menu/button
	Platform  string     `json:"platform"` // admin/h5
	Status    string     `json:"status"`
	Children  []MenuResp `json:"children,optional"`
	CreatedAt string     `json:"createdAt"`
}

type OrderResp struct {
	Id         int64             `json:"id"`
	CampaignId int64             `json:"campaignId"`
	Phone      string            `json:"phone"`
	FormData   map[string]string `json:"formData"`
	ReferrerId int64             `json:"referrerId"`
	Status     string            `json:"status"`
	Amount     float64           `json:"amount"`
	CreatedAt  string            `json:"createdAt"`
}

type OrderListResp struct {
	Total  int64       `json:"total"`
	Orders []OrderResp `json:"orders"`
}

type PageConfigReq struct {
	Id         int64                    `path:"id"`
	Components []map[string]interface{} `json:"components"`
	Theme      map[string]interface{}   `json:"theme"`
}

type GetPageConfigReq struct {
	Id int64 `path:"id"`
}

type PageConfigResp struct {
	Id         int64                    `json:"id"`
	CampaignId int64                    `json:"campaignId"`
	Components []map[string]interface{} `json:"components"`
	Theme      map[string]interface{}   `json:"theme"`
	CreatedAt  string                   `json:"createdAt"`
	UpdatedAt  string                   `json:"updatedAt"`
}

type PasswordPolicyResp struct {
	Id                    int64  `json:"id"`
	MinLength             int    `json:"minLength"`
	RequireUppercase      bool   `json:"requireUppercase"`
	RequireLowercase      bool   `json:"requireLowercase"`
	RequireNumbers        bool   `json:"requireNumbers"`
	RequireSpecialChars   bool   `json:"requireSpecialChars"`
	MaxAge                int    `json:"maxAge"`
	HistoryCount          int    `json:"historyCount"`
	MaxLoginAttempts      int    `json:"maxLoginAttempts"`
	LockoutDuration       int    `json:"lockoutDuration"`
	SessionTimeout        int    `json:"sessionTimeout"`
	MaxConcurrentSessions int    `json:"maxConcurrentSessions"`
	CreatedAt             string `json:"createdAt"`
	UpdatedAt             string `json:"updatedAt"`
}

type PasswordStrengthResp struct {
	Score   int    `json:"score"`
	Level   string `json:"level"`
	Message string `json:"message"`
}

type PaymentCallbackReq struct {
	OrderId   int64   `json:"orderId"`
	PayStatus string  `json:"payStatus"`
	Amount    float64 `json:"amount"`
	TradeNo   string  `json:"tradeNo"`
}

type PaymentQrcodeResp struct {
	QrcodeUrl    string  `json:"qrcodeUrl"`
	Amount       float64 `json:"amount"`
	CampaignName string  `json:"campaignName"`
}

type PermissionResp struct {
	Id          int64  `json:"id"`
	Name        string `json:"name"`
	Code        string `json:"code"`
	Resource    string `json:"resource"`
	Action      string `json:"action"`
	Description string `json:"description"`
}

type PosterRecordResp struct {
	Id             int64  `json:"id"`
	RecordType     string `json:"recordType"`
	CampaignId     int64  `json:"campaignId"`
	DistributorId  int64  `json:"distributorId"`
	TemplateName   string `json:"templateName"`
	PosterUrl      string `json:"posterUrl"`
	ThumbnailUrl   string `json:"thumbnailUrl"`
	FileSize       string `json:"fileSize"`
	GenerationTime int    `json:"generationTime"`
	DownloadCount  int    `json:"downloadCount"`
	ShareCount     int    `json:"shareCount"`
	GeneratedBy    int64  `json:"generatedBy,optional"`
	Status         string `json:"status"`
	CreatedAt      string `json:"createdAt"`
}

type PosterRecordsListResp struct {
	Total   int64              `json:"total"`
	Records []PosterRecordResp `json:"records"`
}

type PosterTemplateConfigListResp struct {
	Total     int64                      `json:"total"`
	Templates []PosterTemplateConfigResp `json:"templates"`
}

type PosterTemplateConfigResp struct {
	Id           int64                  `json:"id"`
	Name         string                 `json:"name"`
	PreviewImage string                 `json:"previewImage"`
	Config       map[string]interface{} `json:"config"`
	Status       string                 `json:"status"`
	CreatedAt    string                 `json:"createdAt"`
	UpdatedAt    string                 `json:"updatedAt"`
}

type RefreshTokenReq struct {
	Token string `json:"token"`
}

type RefreshTokenResp struct {
	Token string `json:"token"`
}

type RegisterReq struct {
	Username string `json:"username"`
	Password string `json:"password"`
	Phone    string `json:"phone"`
	Email    string `json:"email,optional"`
	RealName string `json:"realName,optional"`
}

type RetrySyncResp struct {
	OrderId int64  `json:"orderId"`
	Message string `json:"message"`
	TaskId  string `json:"taskId"`
}

type RewardResp struct {
	Id        int64   `json:"id"`
	UserId    int64   `json:"userId"`
	OrderId   int64   `json:"orderId"`
	Amount    float64 `json:"amount"`
	Status    string  `json:"status"`
	CreatedAt string  `json:"createdAt"`
}

type RoleMenuReq struct {
	RoleId  int64   `json:"roleId"`
	MenuIds []int64 `json:"menuIds"`
}

type RolePermissionReq struct {
	RoleId        int64   `json:"roleId"`
	PermissionIds []int64 `json:"permissionIds"`
}

type RoleResp struct {
	Id          int64    `json:"id"`
	Name        string   `json:"name"`
	Code        string   `json:"code"`
	Description string   `json:"description"`
	Permissions []string `json:"permissions,optional"`
	CreatedAt   string   `json:"createdAt"`
}

type ScanOrderReq struct {
	Code string `json:"code" form:"code"`
}

type ScanOrderResp struct {
	OrderId   int64             `json:"orderId"`
	Status    string            `json:"status"`
	PayStatus string            `json:"payStatus"`
	MemberId  *int64            `json:"memberId"`
	Phone     string            `json:"phone"`
	FormData  map[string]string `json:"formData"`
}

type SecurityEventListResp struct {
	Total  int64               `json:"total"`
	Events []SecurityEventResp `json:"events"`
}

type SecurityEventResp struct {
	Id          int64  `json:"id"`
	EventType   string `json:"eventType"`
	Severity    string `json:"severity"`
	UserId      int64  `json:"userId,optional"`
	Username    string `json:"username"`
	ClientIp    string `json:"clientIp"`
	UserAgent   string `json:"userAgent"`
	Description string `json:"description"`
	Details     string `json:"details"`
	Handled     bool   `json:"handled"`
	HandledBy   int64  `json:"handledBy,optional"`
	HandledAt   string `json:"handledAt,optional"`
	CreatedAt   string `json:"createdAt"`
}

type SendCodeReq struct {
	Target string `json:"target"` // 手机号或邮箱
	Type   string `json:"type"`   // phone/email
}

type SetDistributorLevelRewardReq struct {
	Level            int64   `json:"level"`            // 1/2/3
	RewardPercentage float64 `json:"rewardPercentage"` // 百分比，如 5.5 表示 5.5%
}

type SetDistributorLevelRewardsReq struct {
	Rewards []SetDistributorLevelRewardReq `json:"rewards"`
}

type SubordinateListResp struct {
	Total        int64             `json:"total"`
	Subordinates []SubordinateResp `json:"subordinates"`
}

type SubordinateResp struct {
	Id            int64   `json:"id"`
	UserId        int64   `json:"userId"`
	Username      string  `json:"username,optional"`
	Level         int     `json:"level"`
	TotalOrders   int     `json:"totalOrders"`
	TotalEarnings float64 `json:"totalEarnings"`
	CreatedAt     string  `json:"createdAt"`
}

type SyncHealthResp struct {
	Status   string                 `json:"status"`
	Database map[string]interface{} `json:"database"`
	Queue    map[string]interface{} `json:"queue"`
}

type SyncStatsResp struct {
	TotalSyncs   int64   `json:"totalSyncs"`
	SuccessSyncs int64   `json:"successSyncs"`
	FailedSyncs  int64   `json:"failedSyncs"`
	SuccessRate  float64 `json:"successRate"`
	AvgTime      string  `json:"avgTime"`
}

type SyncStatusResp struct {
	OrderId    int64  `json:"orderId"`
	SyncStatus string `json:"syncStatus"`
	SyncTime   string `json:"syncTime,optional"`
	Attempts   int    `json:"attempts"`
	ErrorMsg   string `json:"errorMsg,optional"`
}

type UnverifyOrderReq struct {
	Code string `json:"code" form:"code"`
}

type UnverifyOrderResp struct {
	OrderId int64  `json:"orderId"`
	Status  string `json:"status"`
}

type UpdateBrandReq struct {
	Name        string `json:"name,optional"`
	Logo        string `json:"logo,optional"`
	Description string `json:"description,optional"`
	Status      string `json:"status,optional"` // active/disabled
}

type UpdateCampaignReq struct {
	BrandId     int64       `json:"brandId,optional"`
	Name        string      `json:"name,optional"`
	Description string      `json:"description,optional"`
	FormFields  []FormField `json:"formFields,optional"` // 动态表单字段
	RewardRule  float64     `json:"rewardRule,optional"` // 奖励规则（金额）
	StartTime   string      `json:"startTime,optional"`
	EndTime     string      `json:"endTime,optional"`
	Status      string      `json:"status,optional"` // 活动状态：active, paused, ended
}

type UpdateDistributorLevelReq struct {
	Level int `json:"level"` // 1-3
}

type UpdateDistributorStatusReq struct {
	Status string `json:"status"` // active/suspended
	Reason string `json:"reason,optional"`
}

type UpdateMenuReq struct {
	Name     string `json:"name,optional"`
	Code     string `json:"code,optional"`
	Path     string `json:"path,optional"`
	Icon     string `json:"icon,optional"`
	ParentId int64  `json:"parentId,optional"`
	Sort     int    `json:"sort,optional"`
	Type     string `json:"type,optional"`
	Platform string `json:"platform,optional"`
	Status   string `json:"status,optional"`
}

type UpdatePasswordPolicyReq struct {
	MinLength             int  `json:"minLength,optional"`
	RequireUppercase      bool `json:"requireUppercase,optional"`
	RequireLowercase      bool `json:"requireLowercase,optional"`
	RequireNumbers        bool `json:"requireNumbers,optional"`
	RequireSpecialChars   bool `json:"requireSpecialChars,optional"`
	MaxAge                int  `json:"maxAge,optional"`
	HistoryCount          int  `json:"historyCount,optional"`
	MaxLoginAttempts      int  `json:"maxLoginAttempts,optional"`
	LockoutDuration       int  `json:"lockoutDuration,optional"`
	SessionTimeout        int  `json:"sessionTimeout,optional"`
	MaxConcurrentSessions int  `json:"maxConcurrentSessions,optional"`
}

type UpdateProfileReq struct {
	RealName string `json:"realName"`
}

type UserInfoResp struct {
	Id        int64    `json:"id"`
	Username  string   `json:"username"`
	Phone     string   `json:"phone"`
	Email     string   `json:"email"`
	RealName  string   `json:"realName"`
	Avatar    string   `json:"avatar"`
	Status    string   `json:"status"`
	Roles     []string `json:"roles"`
	BrandIds  []int64  `json:"brandIds,optional"`
	CreatedAt string   `json:"createdAt"`
}

type UserMenuResp struct {
	UserId   int64      `json:"userId"`
	Platform string     `json:"platform"`
	Menus    []MenuResp `json:"menus"`
}

type UserPermissionResp struct {
	UserId      int64    `json:"userId"`
	Roles       []string `json:"roles"`
	Permissions []string `json:"permissions"`
	BrandIds    []int64  `json:"brandIds,optional"`
}

type UserSessionListResp struct {
	Total    int64             `json:"total"`
	Sessions []UserSessionResp `json:"sessions"`
}

type UserSessionResp struct {
	Id           string `json:"id"`
	UserId       int64  `json:"userId"`
	ClientIp     string `json:"clientIp"`
	UserAgent    string `json:"userAgent"`
	LoginAt      string `json:"loginAt"`
	LastActiveAt string `json:"lastActiveAt"`
	ExpiresAt    string `json:"expiresAt"`
	Status       string `json:"status"`
	CreatedAt    string `json:"createdAt"`
}

type VerificationRecordResp struct {
	Id                 int64  `json:"id"`
	OrderId            int64  `json:"orderId"`
	VerificationStatus string `json:"verificationStatus"`
	VerifiedAt         string `json:"verifiedAt,optional"`
	VerifiedBy         int64  `json:"verifiedBy,optional"`
	VerificationCode   string `json:"verificationCode"`
	VerificationMethod string `json:"verificationMethod"`
	Remark             string `json:"remark"`
	CreatedAt          string `json:"createdAt"`
}

type VerificationRecordsListResp struct {
	Total   int64                    `json:"total"`
	Records []VerificationRecordResp `json:"records"`
}

type VerifyOrderReq struct {
	Code string `json:"code" form:"code"`
}

type VerifyOrderResp struct {
	OrderId    int64  `json:"orderId"`
	Status     string `json:"status"`
	VerifiedAt string `json:"verifiedAt"`
}

type WithdrawalApplyReq struct {
	Amount      float64 `json:"amount"`
	BankName    string  `json:"bankName"`
	BankAccount string  `json:"bankAccount"`
	AccountName string  `json:"accountName"`
}

type WithdrawalApproveReq struct {
	Status string `json:"status"` // approved/rejected
	Remark string `json:"remark,optional"`
}

type WithdrawalListResp struct {
	Total       int64            `json:"total"`
	Withdrawals []WithdrawalResp `json:"withdrawals"`
}

type WithdrawalResp struct {
	Id          int64   `json:"id"`
	UserId      int64   `json:"userId"`
	Username    string  `json:"username,optional"`
	RealName    string  `json:"realName,optional"`
	Amount      float64 `json:"amount"`
	BankName    string  `json:"bankName"`
	BankAccount string  `json:"bankAccount"`
	AccountName string  `json:"accountName"`
	Status      string  `json:"status"`
	Remark      string  `json:"remark,optional"`
	ApprovedBy  int64   `json:"approvedBy,optional"`
	ApprovedAt  string  `json:"approvedAt,optional"`
	CreatedAt   string  `json:"createdAt"`
}

// ============================================
// 会员管理相关类型
// ============================================
type (
	// 会员响应
	MemberResp struct {
		Id        int64  `json:"id"`
		UnionID   string `json:"unionid"`
		Nickname  string `json:"nickname"`
		Avatar    string `json:"avatar"`
		Phone     string `json:"phone"`
		Gender    int    `json:"gender"`
		Source    string `json:"source"`
		Status    string `json:"status"`
		CreatedAt string `json:"createdAt"`
		UpdatedAt string `json:"updatedAt"`
	}
	// 会员画像响应
	MemberProfileResp struct {
		MemberId              int64   `json:"memberId"`
		TotalOrders           int     `json:"totalOrders"`
		TotalPayment          float64 `json:"totalPayment"`
		TotalReward           float64 `json:"totalReward"`
		FirstOrderAt          string  `json:"firstOrderAt"`
		LastOrderAt           string  `json:"lastOrderAt"`
		FirstPaymentAt        string  `json:"firstPaymentAt"`
		LastPaymentAt         string  `json:"lastPaymentAt"`
		ParticipatedCampaigns int     `json:"participatedCampaigns"`
	}
	// 获取会员列表请求
	GetMembersReq struct {
		Page     int64  `json:"page,optional" form:"page,optional"`
		PageSize int64  `json:"pageSize,optional" form:"pageSize,optional"`
		Status   string `json:"status,optional" form:"status,optional"`
		Keyword  string `json:"keyword,optional" form:"keyword,optional"`
		Source   string `json:"source,optional" form:"source,optional"`
		Gender   int    `json:"gender,optional" form:"gender,optional"`
	}
	// 获取会员列表响应
	GetMembersResp struct {
		Total   int64        `json:"total"`
		Members []MemberResp `json:"members"`
	}
	// 更新会员信息请求
	UpdateMemberReq struct {
		Nickname string `json:"nickname,optional"`
		Avatar   string `json:"avatar,optional"`
		Gender   int    `json:"gender,optional"`
	}
	// 更新会员状态请求
	UpdateMemberStatusReq struct {
		Status string `json:"status"`
	}
	// 获取会员请求
	GetMemberReq struct {
		Id int64 `path:"id" json:"id"`
	}
	// 数据统计请求类型
	GetDashboardStatsReq struct {
		BrandId   int64  `path:"brandId,optional" form:"brandId,optional"`
		StartDate string `path:"startDate,optional" form:"startDate,optional"`
		EndDate   string `path:"endDate,optional" form:"endDate,optional"`
		Period    string `path:"period,optional" form:"period,optional"` // day/week/month/year
	}
	// 数据统计响应类型
	DashboardStatsResp struct {
		TotalOrders     int64              `json:"totalOrders"`
		TotalRevenue    float64            `json:"totalRevenue"`
		TodayOrders     int64              `json:"todayOrders"`
		TodayRevenue    float64            `json:"todayRevenue"`
		WeekOrders      int64              `json:"weekOrders"`
		WeekRevenue     float64            `json:"weekRevenue"`
		MonthOrders     int64              `json:"monthOrders"`
		MonthRevenue    float64            `json:"monthRevenue"`
		OrderTrend      []TrendData        `json:"orderTrend"`
		RevenueTrend    []TrendData        `json:"revenueTrend"`
		TopCampaigns    []CampaignStats    `json:"topCampaigns"`
		TopDistributors []DistributorStats `json:"topDistributors"`
	}
	// 趋势数据
	TrendData struct {
		Date  string `json:"date"`
		Value int64  `json:"value"`
	}
	// 活动统计
	CampaignStats struct {
		Id               int64   `json:"id"`
		Name             string  `json:"name"`
		OrderCount       int64   `json:"orderCount"`
		Revenue          float64 `json:"revenue"`
		ParticipantCount int64   `json:"participantCount"`
	}
	// 分销商统计
	DistributorStats struct {
		Id                int64   `json:"id"`
		Username          string  `json:"username,optional"`
		Level             int     `json:"level"`
		TotalOrders       int64   `json:"totalOrders"`
		TotalRevenue      float64 `json:"totalRevenue"`
		SubordinatesCount int     `json:"subordinatesCount,optional"`
	}
	// 导出报告请求
	ExportReportReq struct {
		ReportType string `path:"reportType" form:"reportType"` // orders/revenue/campaigns/distributors
		BrandId    int64  `path:"brandId,optional" form:"brandId,optional"`
		StartDate  string `path:"startDate,optional" form:"startDate,optional"`
		EndDate    string `path:"endDate,optional" form:"endDate,optional"`
		Format     string `path:"format,optional" form:"format,optional"` // csv/excel/json
	}
	// 导出报告响应
	ExportReportResp struct {
		FileUrl  string `json:"fileUrl"`
		Filename string `json:"filename"`
	}
)
