// Code generated by goctl. DO NOT EDIT.
package reward

import (
	"context"
	"testing"
	"time"

	"dmh/api/internal/handler/testutil"
	"dmh/api/internal/svc"
	"dmh/api/internal/types"
	"dmh/model"

	"github.com/stretchr/testify/assert"
	"gorm.io/gorm"
)

func setupRewardTestDB(t *testing.T) *gorm.DB {
	t.Helper()
	db := testutil.SetupGormTestDB(t)
	db.AutoMigrate(&model.Brand{}, &model.Campaign{}, &model.Distributor{}, &model.User{}, &model.DistributorReward{}, &model.UserBalance{}, &model.Order{})
	testutil.ClearTables(db, "distributor_rewards", "user_balances", "orders", "distributors", "campaigns", "brands", "users")
	return db
}

func TestGetRewardsLogic(t *testing.T) {
	db := setupRewardTestDB(t)

	brand := &model.Brand{Id: 1, Name: "Brand1", Status: "active"}
	campaign := &model.Campaign{Id: 1, BrandId: 1, Name: "C1", Status: "active", StartTime: time.Now().Add(-time.Hour), EndTime: time.Now().Add(time.Hour), RewardRule: 10}

	distributor := &model.Distributor{
		Id:      1,
		UserId:  1,
		BrandId: 1,
		Level:   1,
		Status:  "active",
	}
	user := &model.User{
		Id:       1,
		Username: "testuser",
		Phone:    "13800138000",
	}
	order := &model.Order{
		Id:         1,
		CampaignId: 1,
		Phone:      "13800138001",
		FormData:   "{}",
		Status:     "paid",
		Amount:     100,
	}
	db.Create(brand)
	db.Create(campaign)
	db.Create(user)
	db.Create(distributor)
	db.Create(order)

	reward := &model.DistributorReward{
		Id:            1,
		DistributorId: 1,
		UserId:        1,
		OrderId:       1,
		CampaignId:    1,
		Amount:        10,
		Level:         1,
		RewardRate:    0.1,
		Status:        "settled",
	}
	db.Create(reward)

	svcCtx := &svc.ServiceContext{DB: db}
	logic := NewGetRewardsLogic(context.Background(), svcCtx)

	tests := []struct {
		name        string
		req         *types.GetRewardsReq
		expectError bool
		expectCount int
	}{
		{
			name:        "获取所有奖励",
			req:         &types.GetRewardsReq{},
			expectError: false,
			expectCount: 1,
		},
		{
			name: "按用户筛选",
			req: &types.GetRewardsReq{
				UserId: 1,
			},
			expectError: false,
			expectCount: 1,
		},
		{
			name: "按订单筛选",
			req: &types.GetRewardsReq{
				OrderId: 1,
			},
			expectError: false,
			expectCount: 1,
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			resp, err := logic.GetRewards(tt.req)

			if tt.expectError {
				assert.Error(t, err)
			} else {
				assert.NoError(t, err)
				assert.Len(t, resp, tt.expectCount)
			}
		})
	}
}

func TestGetBalanceLogic(t *testing.T) {
	db := setupRewardTestDB(t)

	balance := &model.UserBalance{
		UserId:      1,
		Balance:     500,
		TotalReward: 1000,
	}
	db.Create(balance)

	svcCtx := &svc.ServiceContext{DB: db}
	logic := NewGetBalanceLogic(context.Background(), svcCtx)

	tests := []struct {
		name        string
		userId      int64
		expectError bool
		expectResp  *types.BalanceResp
	}{
		{
			name:        "成功获取余额",
			userId:      1,
			expectError: false,
			expectResp: &types.BalanceResp{
				UserId:      1,
				Balance:     500,
				TotalReward: 1000,
			},
		},
		{
			name:        "用户不存在",
			userId:      999,
			expectError: true,
			expectResp:  nil,
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			resp, err := logic.GetBalance(tt.userId)

			if tt.expectError {
				assert.Error(t, err)
				assert.Nil(t, resp)
			} else {
				assert.NoError(t, err)
				assert.NotNil(t, resp)
				assert.Equal(t, tt.expectResp.UserId, resp.UserId)
				assert.Equal(t, tt.expectResp.Balance, resp.Balance)
				assert.Equal(t, tt.expectResp.TotalReward, resp.TotalReward)
			}
		})
	}
}
