// Code generated by goctl. DO NOT EDIT.
package menu

import (
	"context"
	"testing"

	"dmh/api/internal/svc"
	"dmh/api/internal/types"
	"dmh/model"

	"github.com/stretchr/testify/assert"
	"gorm.io/driver/sqlite"
	"gorm.io/gorm"
)

func setupMenuTestDB() *gorm.DB {
	db, _ := gorm.Open(sqlite.Open(":memory:"), &gorm.Config{})
	db.AutoMigrate(&model.Menu{}, &model.RoleMenu{}, &model.UserRole{}, &model.User{}, &model.Role{})
	return db
}

func TestCreateMenuLogic(t *testing.T) {
	db := setupMenuTestDB()

	svcCtx := &svc.ServiceContext{DB: db}
	logic := NewCreateMenuLogic(context.Background(), svcCtx)

	req := &types.CreateMenuReq{
		Name:     "活动管理",
		Code:     "campaign",
		Path:     "/campaign",
		Icon:     "activity",
		Sort:     1,
		Type:     "menu",
		Platform: "admin",
	}

	resp, err := logic.CreateMenu(req)

	assert.NoError(t, err)
	assert.NotNil(t, resp)
	assert.Equal(t, "活动管理", resp.Name)
	assert.Equal(t, "campaign", resp.Code)
}

func TestUpdateMenuLogic(t *testing.T) {
	db := setupMenuTestDB()

	menu := &model.Menu{
		ID:       1,
		Name:     "活动管理",
		Code:     "campaign",
		Path:     "/campaign",
		Sort:     1,
		Type:     "menu",
		Platform: "admin",
		Status:   "active",
	}
	db.Create(menu)

	svcCtx := &svc.ServiceContext{DB: db}
	logic := NewUpdateMenuLogic(context.Background(), svcCtx)

	req := &types.UpdateMenuReq{
		Name:   "活动管理2",
		Status: "disabled",
	}

	resp, err := logic.UpdateMenu(1, req)

	assert.NoError(t, err)
	assert.NotNil(t, resp)
	assert.Equal(t, "活动管理2", resp.Name)
	assert.Equal(t, "disabled", resp.Status)
}

func TestDeleteMenuLogic(t *testing.T) {
	db := setupMenuTestDB()

	menu := &model.Menu{
		ID:       1,
		Name:     "测试菜单",
		Code:     "test",
		Path:     "/test",
		Type:     "menu",
		Platform: "admin",
		Status:   "active",
	}
	db.Create(menu)

	svcCtx := &svc.ServiceContext{DB: db}
	logic := NewDeleteMenuLogic(context.Background(), svcCtx)

	resp, err := logic.DeleteMenu(1)

	assert.NoError(t, err)
	assert.NotNil(t, resp)

	var count int64
	db.Model(&model.Menu{}).Where("id = ?", 1).Count(&count)
	assert.Equal(t, int64(0), count)
}

func TestGetMenuLogic(t *testing.T) {
	db := setupMenuTestDB()

	menu := &model.Menu{
		ID:       1,
		Name:     "活动管理",
		Code:     "campaign",
		Path:     "/campaign",
		Sort:     1,
		Type:     "menu",
		Platform: "admin",
		Status:   "active",
	}
	db.Create(menu)

	svcCtx := &svc.ServiceContext{DB: db}
	logic := NewGetMenuLogic(context.Background(), svcCtx)

	resp, err := logic.GetMenu(1)

	assert.NoError(t, err)
	assert.NotNil(t, resp)
	assert.Equal(t, "活动管理", resp.Name)
	assert.Equal(t, "campaign", resp.Code)
}

func TestGetMenusLogic(t *testing.T) {
	db := setupMenuTestDB()

	menus := []model.Menu{
		{ID: 1, Name: "活动管理", Code: "campaign", Path: "/campaign", Sort: 1, Type: "menu", Platform: "admin", Status: "active"},
		{ID: 2, Name: "用户管理", Code: "user", Path: "/user", Sort: 2, Type: "menu", Platform: "admin", Status: "active"},
		{ID: 3, Name: "创建活动", Code: "campaign:create", Path: "", Sort: 1, Type: "button", Platform: "admin", Status: "active", ParentID: &[]int64{1}[0]},
	}
	db.Create(&menus)

	svcCtx := &svc.ServiceContext{DB: db}
	logic := NewGetMenusLogic(context.Background(), svcCtx)

	resp, err := logic.GetMenus(&types.GetMenusReq{
		Platform: "admin",
	})

	assert.NoError(t, err)
	assert.NotNil(t, resp)
	assert.Len(t, resp.Menus, 2)
}

func TestGetUserMenusLogic(t *testing.T) {
	db := setupMenuTestDB()

	user := &model.User{
		Id:       1,
		Username: "testuser",
		Phone:    "13800138000",
	}
	role := &model.Role{
		ID:   1,
		Name: "管理员",
		Code: "admin",
	}
	menu1 := &model.Menu{
		ID:       1,
		Name:     "活动管理",
		Code:     "campaign",
		Path:     "/campaign",
		Sort:     1,
		Type:     "menu",
		Platform: "admin",
		Status:   "active",
	}
	menu2 := &model.Menu{
		ID:       2,
		Name:     "创建活动",
		Code:     "campaign:create",
		Path:     "",
		Sort:     1,
		Type:     "button",
		Platform: "admin",
		Status:   "active",
		ParentID: &[]int64{1}[0],
	}
	db.Create(user)
	db.Create(role)
	db.Create(menu1)
	db.Create(menu2)

	userRole := &model.UserRole{
		UserID: 1,
		RoleID: 1,
	}
	db.Create(userRole)

	roleMenu1 := &model.RoleMenu{
		RoleID: 1,
		MenuID: 1,
	}
	roleMenu2 := &model.RoleMenu{
		RoleID: 1,
		MenuID: 2,
	}
	db.Create(roleMenu1)
	db.Create(roleMenu2)

	svcCtx := &svc.ServiceContext{DB: db}
	logic := NewGetUserMenusLogic(context.Background(), svcCtx)

	resp, err := logic.GetUserMenus(1, "admin")

	assert.NoError(t, err)
	assert.NotNil(t, resp)
	assert.Equal(t, int64(1), resp.UserId)
	assert.Equal(t, "admin", resp.Platform)
	if len(resp.Menus) > 0 {
		assert.Equal(t, "活动管理", resp.Menus[0].Name)
		if len(resp.Menus[0].Children) > 0 {
			assert.Equal(t, "创建活动", resp.Menus[0].Children[0].Name)
		}
	}
}

func TestConfigRoleMenusLogic(t *testing.T) {
	db := setupMenuTestDB()

	role := &model.Role{
		ID:   1,
		Name: "管理员",
		Code: "admin",
	}
	menu1 := &model.Menu{
		ID:       1,
		Name:     "活动管理",
		Code:     "campaign",
		Path:     "/campaign",
		Type:     "menu",
		Platform: "admin",
		Status:   "active",
	}
	menu2 := &model.Menu{
		ID:       2,
		Name:     "用户管理",
		Code:     "user",
		Path:     "/user",
		Type:     "menu",
		Platform: "admin",
		Status:   "active",
	}
	db.Create(role)
	db.Create(menu1)
	db.Create(menu2)

	svcCtx := &svc.ServiceContext{DB: db}
	logic := NewConfigRoleMenusLogic(context.Background(), svcCtx)

	req := &types.RoleMenuReq{
		RoleId:  1,
		MenuIds: []int64{1, 2},
	}

	resp, err := logic.ConfigRoleMenus(req)

	assert.NoError(t, err)
	assert.NotNil(t, resp)

	var count int64
	db.Model(&model.RoleMenu{}).Where("role_id = ?", 1).Count(&count)
	assert.Equal(t, int64(2), count)
}
